## 정렬
### index명/컬럼명을 순 정렬
- #### sort_index(axis, ascending=True)
    - axis
        - index명 기준 정렬(행) : 'index' 또는 0 (기본값)
        - columnm 명 기준 정렬(열) : 'columns' 또는 1
    - ascending
        - 정렬방식
        - True(기본): 오름차순, False: 내림차순
    - inplace
        - 원본에 적용 여부
        - False(기본): 변경한 복사본 반환 
        - True : 원본을 변경

In [1]:
import pandas as pd
import numpy as np

movie_df = pd.read_csv('data/movie.csv', index_col='movie_title')
movie_df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
Star Wars: Episode VII - The Force Awakens,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [2]:
movie_df.sort_index() #axis='index', ascending=True (기본값): 행이름, 오름차순

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
#Horror,Color,Tara Subkoff,35.0,101.0,37.0,56.0,Balthazar Getty,501.0,NaN,Drama|Horror|Mystery|Thriller,...,42.0,English,USA,Not Rated,1500000.0,2015.0,418.0,3.3,NaN,750
10 Cloverfield Lane,Color,Dan Trachtenberg,411.0,104.0,16.0,82.0,John Gallagher Jr.,14000.0,71897215.0,Drama|Horror|Mystery|Sci-Fi|Thriller,...,440.0,English,USA,PG-13,15000000.0,2016.0,338.0,7.3,2.35,33000
10 Days in a Madhouse,Color,Timothy Hines,1.0,111.0,0.0,247.0,Kelly LeBrock,1000.0,14616.0,Drama,...,10.0,English,USA,R,12000000.0,2015.0,445.0,7.5,1.85,26000
10 Things I Hate About You,Color,Gil Junger,133.0,97.0,19.0,835.0,Heath Ledger,23000.0,38176108.0,Comedy|Drama|Romance,...,549.0,English,USA,PG-13,16000000.0,1999.0,13000.0,7.2,1.85,10000
"10,000 B.C.",NaN,Christopher Barnard,NaN,22.0,0.0,NaN,NaN,5.0,NaN,Comedy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.2,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
[Rec] 2,Color,Jaume Balagueró,222.0,85.0,57.0,6.0,Pablo Rosso,37.0,27024.0,Horror,...,148.0,Spanish,Spain,R,5600000.0,2009.0,9.0,6.6,1.85,4000
eXistenZ,Color,David Cronenberg,196.0,115.0,0.0,716.0,Sarah Polley,1000.0,2840417.0,Horror|Sci-Fi|Thriller,...,527.0,English,Canada,R,31000000.0,1999.0,900.0,6.8,1.85,6000
xXx,Color,Rob Cohen,191.0,132.0,357.0,212.0,Eve,14000.0,141204016.0,Action|Adventure|Thriller,...,737.0,English,USA,PG-13,70000000.0,2002.0,223.0,5.8,2.35,10000
xXx: State of the Union,Color,Lee Tamahori,77.0,101.0,93.0,218.0,Nona Gaye,287.0,26082914.0,Action|Adventure|Crime|Thriller,...,213.0,English,USA,PG-13,87000000.0,2005.0,233.0,4.3,2.35,0
Æon Flux,Color,Karyn Kusama,178.0,93.0,45.0,352.0,Sophie Okonedo,9000.0,25857987.0,Action|Sci-Fi,...,532.0,English,USA,PG-13,62000000.0,2005.0,460.0,5.5,2.35,0

In [4]:
#문자열 : 특수문자 < 숫자 < 대문자 < 소문자 < 외국어
movie_df.sort_index(ascending=False) #내림차순

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Æon Flux,Color,Karyn Kusama,178.0,93.0,45.0,352.0,Sophie Okonedo,9000.0,25857987.0,Action|Sci-Fi,...,532.0,English,USA,PG-13,62000000.0,2005.0,460.0,5.5,2.35,0
xXx: State of the Union,Color,Lee Tamahori,77.0,101.0,93.0,218.0,Nona Gaye,287.0,26082914.0,Action|Adventure|Crime|Thriller,...,213.0,English,USA,PG-13,87000000.0,2005.0,233.0,4.3,2.35,0
xXx,Color,Rob Cohen,191.0,132.0,357.0,212.0,Eve,14000.0,141204016.0,Action|Adventure|Thriller,...,737.0,English,USA,PG-13,70000000.0,2002.0,223.0,5.8,2.35,10000
eXistenZ,Color,David Cronenberg,196.0,115.0,0.0,716.0,Sarah Polley,1000.0,2840417.0,Horror|Sci-Fi|Thriller,...,527.0,English,Canada,R,31000000.0,1999.0,900.0,6.8,1.85,6000
[Rec] 2,Color,Jaume Balagueró,222.0,85.0,57.0,6.0,Pablo Rosso,37.0,27024.0,Horror,...,148.0,Spanish,Spain,R,5600000.0,2009.0,9.0,6.6,1.85,4000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"10,000 B.C.",NaN,Christopher Barnard,NaN,22.0,0.0,NaN,NaN,5.0,NaN,Comedy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.2,NaN,0
10 Things I Hate About You,Color,Gil Junger,133.0,97.0,19.0,835.0,Heath Ledger,23000.0,38176108.0,Comedy|Drama|Romance,...,549.0,English,USA,PG-13,16000000.0,1999.0,13000.0,7.2,1.85,10000
10 Days in a Madhouse,Color,Timothy Hines,1.0,111.0,0.0,247.0,Kelly LeBrock,1000.0,14616.0,Drama,...,10.0,English,USA,R,12000000.0,2015.0,445.0,7.5,1.85,26000
10 Cloverfield Lane,Color,Dan Trachtenberg,411.0,104.0,16.0,82.0,John Gallagher Jr.,14000.0,71897215.0,Drama|Horror|Mystery|Sci-Fi|Thriller,...,440.0,English,USA,PG-13,15000000.0,2016.0,338.0,7.3,2.35,33000
#Horror,Color,Tara Subkoff,35.0,101.0,37.0,56.0,Balthazar Getty,501.0,NaN,Drama|Horror|Mystery|Thriller,...,42.0,English,USA,Not Rated,1500000.0,2015.0,418.0,3.3,NaN,750

In [5]:
movie_df.sort_index(axis='columns')

,actor_1_facebook_likes,actor_1_name,actor_2_facebook_likes,actor_2_name,actor_3_facebook_likes,actor_3_name,aspect_ratio,budget,cast_total_facebook_likes,color,...,gross,imdb_score,language,movie_facebook_likes,movie_imdb_link,num_critic_for_reviews,num_user_for_reviews,num_voted_users,plot_keywords,title_year
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,1000.0,CCH Pounder,936.0,Joel David Moore,855.0,Wes Studi,1.78,237000000.0,4834,Color,...,760505847.0,7.9,English,33000,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,723.0,3054.0,886204,avatar|future|marine|native|paraplegic,2009.0
Pirates of the Caribbean: At World's End,40000.0,Johnny Depp,5000.0,Orlando Bloom,1000.0,Jack Davenport,2.35,300000000.0,48350,Color,...,309404152.0,7.1,English,0,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,302.0,1238.0,471220,goddess|marriage ceremony|marriage proposal|pi...,2007.0
Spectre,11000.0,Christoph Waltz,393.0,Rory Kinnear,161.0,Stephanie Sigman,2.35,245000000.0,11700,Color,...,200074175.0,6.8,English,85000,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,602.0,994.0,275868,bomb|espionage|sequel|spy|terrorist,2015.0
The Dark Knight Rises,27000.0,Tom Hardy,23000.0,Christian Bale,23000.0,Joseph Gordon-Levitt,2.35,250000000.0,106759,Color,...,448130642.0,8.5,English,164000,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,813.0,2701.0,1144337,deception|imprisonment|lawlessness|police offi...,2012.0
Star Wars: Episode VII - The Force Awakens,131.0,Doug Walker,12.0,Rob Walker,NaN,NaN,NaN,NaN,143,NaN,...,NaN,7.1,NaN,0,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Signed Sealed Delivered,637.0,Eric Mabius,470.0,Daphne Zuniga,318.0,Crystal Lowe,NaN,NaN,2283,Color,...,NaN,7.7,English,84,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,1.0,6.0,629,fraud|postal worker|prison|theft|trial,2013.0
The Following,841.0,Natalie Zea,593.0,Valorie Curry,319.0,Sam Underwood,16.00,NaN,1753,Color,...,NaN,7.5,English,32000,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,43.0,359.0,73839,cult|fbi|hideout|prison escape|serial killer,NaN
A Plague So Pleasant,0.0,Eva Boehnke,0.0,Maxwell Moody,0.0,David Chandler,NaN,1400.0,0,Color,...,NaN,6.3,English,16,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,13.0,3.0,38,NaN,2013.0
Shanghai Calling,946.0,Alan Ruck,719.0,Daniel Henney,489.0,Eliza Coupe,2.35,NaN,2386,Color,...,10443.0,6.3,English,660,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,14.0,9.0,1255,NaN,2012.0
My Date with Drew,86.0,John August,23.0,Brian Herzlinger,16.0,Jon Gunn,1.85,1100.0,163,Color,...,85222.0,6.6,English,456,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,43.0,84.0,4285,actress name in title|crush|date|four word tit...,2004.0

In [7]:
movie_df.sort_index(axis=1,  ascending=False) #컬럼명 기준 정렬, 내림차순

,title_year,plot_keywords,num_voted_users,num_user_for_reviews,num_critic_for_reviews,movie_imdb_link,movie_facebook_likes,language,imdb_score,gross,...,color,cast_total_facebook_likes,budget,aspect_ratio,actor_3_name,actor_3_facebook_likes,actor_2_name,actor_2_facebook_likes,actor_1_name,actor_1_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Avatar,2009.0,avatar|future|marine|native|paraplegic,886204,3054.0,723.0,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,33000,English,7.9,760505847.0,...,Color,4834,237000000.0,1.78,Wes Studi,855.0,Joel David Moore,936.0,CCH Pounder,1000.0
Pirates of the Caribbean: At World's End,2007.0,goddess|marriage ceremony|marriage proposal|pi...,471220,1238.0,302.0,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,0,English,7.1,309404152.0,...,Color,48350,300000000.0,2.35,Jack Davenport,1000.0,Orlando Bloom,5000.0,Johnny Depp,40000.0
Spectre,2015.0,bomb|espionage|sequel|spy|terrorist,275868,994.0,602.0,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,85000,English,6.8,200074175.0,...,Color,11700,245000000.0,2.35,Stephanie Sigman,161.0,Rory Kinnear,393.0,Christoph Waltz,11000.0
The Dark Knight Rises,2012.0,deception|imprisonment|lawlessness|police offi...,1144337,2701.0,813.0,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,164000,English,8.5,448130642.0,...,Color,106759,250000000.0,2.35,Joseph Gordon-Levitt,23000.0,Christian Bale,23000.0,Tom Hardy,27000.0
Star Wars: Episode VII - The Force Awakens,NaN,NaN,8,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,0,NaN,7.1,NaN,...,NaN,143,NaN,NaN,NaN,NaN,Rob Walker,12.0,Doug Walker,131.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Signed Sealed Delivered,2013.0,fraud|postal worker|prison|theft|trial,629,6.0,1.0,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,84,English,7.7,NaN,...,Color,2283,NaN,NaN,Crystal Lowe,318.0,Daphne Zuniga,470.0,Eric Mabius,637.0
The Following,NaN,cult|fbi|hideout|prison escape|serial killer,73839,359.0,43.0,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,32000,English,7.5,NaN,...,Color,1753,NaN,16.00,Sam Underwood,319.0,Valorie Curry,593.0,Natalie Zea,841.0
A Plague So Pleasant,2013.0,NaN,38,3.0,13.0,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,16,English,6.3,NaN,...,Color,0,1400.0,NaN,David Chandler,0.0,Maxwell Moody,0.0,Eva Boehnke,0.0
Shanghai Calling,2012.0,NaN,1255,9.0,14.0,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,660,English,6.3,10443.0,...,Color,2386,NaN,2.35,Eliza Coupe,489.0,Daniel Henney,719.0,Alan Ruck,946.0
My Date with Drew,2004.0,actress name in title|crush|date|four word tit...,4285,84.0,43.0,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,456,English,6.6,85222.0,...,Color,163,1100.0,1.85,Jon Gunn,16.0,Brian Herzlinger,23.0,John August,86.0

In [10]:
# movie_df['A':'B']

In [11]:
movie_df2 = movie_df.sort_index()
movie_df2.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
#Horror,Color,Tara Subkoff,35.0,101.0,37.0,56.0,Balthazar Getty,501.0,NaN,Drama|Horror|Mystery|Thriller,...,42.0,English,USA,Not Rated,1500000.0,2015.0,418.0,3.3,NaN,750
10 Cloverfield Lane,Color,Dan Trachtenberg,411.0,104.0,16.0,82.0,John Gallagher Jr.,14000.0,71897215.0,Drama|Horror|Mystery|Sci-Fi|Thriller,...,440.0,English,USA,PG-13,15000000.0,2016.0,338.0,7.3,2.35,33000
10 Days in a Madhouse,Color,Timothy Hines,1.0,111.0,0.0,247.0,Kelly LeBrock,1000.0,14616.0,Drama,...,10.0,English,USA,R,12000000.0,2015.0,445.0,7.5,1.85,26000
10 Things I Hate About You,Color,Gil Junger,133.0,97.0,19.0,835.0,Heath Ledger,23000.0,38176108.0,Comedy|Drama|Romance,...,549.0,English,USA,PG-13,16000000.0,1999.0,13000.0,7.2,1.85,10000
"10,000 B.C.",NaN,Christopher Barnard,NaN,22.0,0.0,NaN,NaN,5.0,NaN,Comedy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.2,NaN,0
102 Dalmatians,Color,Kevin Lima,84.0,100.0,36.0,439.0,Eric Idle,2000.0,66941559.0,Adventure|Comedy|Family,...,77.0,English,USA,G,85000000.0,2000.0,795.0,4.8,1.85,372
10th & Wolf,Color,Robert Moresco,26.0,107.0,53.0,463.0,Brad Renfro,954.0,53481.0,Crime|Drama|Thriller,...,34.0,English,USA,R,8000000.0,2006.0,551.0,6.4,2.35,294
11:14,Color,Greg Marcks,68.0,85.0,9.0,407.0,Barbara Hershey,861.0,NaN,Comedy|Crime|Drama,...,133.0,English,USA,R,6000000.0,2003.0,618.0,7.2,1.85,0
12 Angry Men,Black and White,Sidney Lumet,177.0,96.0,0.0,253.0,Lee J. Cobb,359.0,NaN,Crime|Drama,...,888.0,English,USA,Not Rated,350000.0,1957.0,259.0,8.9,1.66,40000
12 Monkeys,Color,NaN,13.0,42.0,NaN,442.0,Kirk Acevedo,757.0,NaN,Adventure|Drama|Mystery|Sci-Fi|Thriller,...,56.0,English,USA,TV-14,NaN,NaN,641.0,7.6,16.00,12000

In [12]:
movie_df2['A':'B'] #index가 sorting 된 경우 부분값을 가지고 slicing가능. stop은 포함 안함.
# A로 시작하는 영화들

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
A Beautiful Mind,Color,Ron Howard,205.0,135.0,2000.0,535.0,Austin Pendleton,1000.0,170708996.0,Biography|Drama,...,1171.0,English,USA,PG-13,58000000.0,2001.0,592.0,8.2,1.85,29000
A Beginner's Guide to Snuff,Color,Mitchell Altieri,NaN,87.0,9.0,165.0,Luke Edwards,467.0,NaN,Comedy|Horror|Thriller,...,NaN,English,USA,NaN,NaN,2016.0,258.0,8.7,NaN,8
A Better Life,Color,Chris Weitz,94.0,98.0,129.0,221.0,Eddie 'Piolin' Sotelo,749.0,1754319.0,Drama|Romance,...,81.0,English,USA,PG-13,10000000.0,2011.0,252.0,7.2,1.85,0
A Bridge Too Far,Black and White,Richard Attenborough,56.0,175.0,0.0,14.0,Dirk Bogarde,385.0,50800000.0,Drama|History|War,...,210.0,English,USA,PG,26000000.0,1977.0,232.0,7.4,2.35,0
A Bug's Life,Color,John Lasseter,117.0,95.0,487.0,1000.0,Madeline Kahn,18000.0,162792677.0,Adventure|Animation|Comedy|Family|Fantasy,...,317.0,English,USA,G,120000000.0,1998.0,1000.0,7.2,2.35,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
Avengers: Age of Ultron,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
Awake,Color,Joby Harold,133.0,84.0,8.0,896.0,Fisher Stevens,4000.0,14373825.0,Crime|Mystery|Thriller,...,196.0,English,USA,R,8600000.0,2007.0,922.0,6.5,2.35,0
Away We Go,Color,Sam Mendes,217.0,98.0,0.0,374.0,Jim Gaffigan,925.0,9430988.0,Comedy|Drama|Romance,...,115.0,English,USA,R,17000000.0,2009.0,472.0,7.1,2.35,7000
Ayurveda: Art of Being,Color,Pan Nalin,15.0,102.0,95.0,NaN,NaN,NaN,16892.0,Documentary,...,12.0,English,India,NaN,300000.0,2001.0,NaN,7.6,1.85,379

In [13]:
movie_df2['A B':'A C']

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
A Beautiful Mind,Color,Ron Howard,205.0,135.0,2000.0,535.0,Austin Pendleton,1000.0,170708996.0,Biography|Drama,...,1171.0,English,USA,PG-13,58000000.0,2001.0,592.0,8.2,1.85,29000
A Beginner's Guide to Snuff,Color,Mitchell Altieri,NaN,87.0,9.0,165.0,Luke Edwards,467.0,NaN,Comedy|Horror|Thriller,...,NaN,English,USA,NaN,NaN,2016.0,258.0,8.7,NaN,8
A Better Life,Color,Chris Weitz,94.0,98.0,129.0,221.0,Eddie 'Piolin' Sotelo,749.0,1754319.0,Drama|Romance,...,81.0,English,USA,PG-13,10000000.0,2011.0,252.0,7.2,1.85,0
A Bridge Too Far,Black and White,Richard Attenborough,56.0,175.0,0.0,14.0,Dirk Bogarde,385.0,50800000.0,Drama|History|War,...,210.0,English,USA,PG,26000000.0,1977.0,232.0,7.4,2.35,0
A Bug's Life,Color,John Lasseter,117.0,95.0,487.0,1000.0,Madeline Kahn,18000.0,162792677.0,Adventure|Animation|Comedy|Family|Fantasy,...,317.0,English,USA,G,120000000.0,1998.0,1000.0,7.2,2.35,0

### 컬럼 값 기준 정렬
- #### sort_values(by, ascending, inplace)
    - by
        - 정렬기준 컬럼명
        - 여러 컬럼에 대해 정렬할 경우 리스트에 담아 전달
    - ascending
        - 정렬방식
        - True(기본): 오름차순, False: 내림차순
        - 여러컬럼에 대해 정렬할 경우 정렬방식도 리스트에 담아 전달
    - inplace
        - 원본에 적용 여부
        - False(기본): 변경한 복사본 반환 
        - True : 원본을 변경

In [15]:
movie_df.sort_values('director_name') #director_name값들을 기준으로 정렬. 오름차순

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
The Helix... Loaded,Color,A. Raven Cruz,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
Circle,Color,Aaron Hann,29.0,87.0,0.0,94.0,Michael McLafferty,160.0,NaN,Drama|Horror|Mystery|Sci-Fi|Thriller,...,59.0,English,USA,Not Rated,NaN,2015.0,152.0,6.0,NaN,0
Get Low,Color,Aaron Schneider,160.0,100.0,11.0,970.0,Robert Duvall,13000.0,9176553.0,Drama|Mystery,...,97.0,English,USA,PG-13,7500000.0,2009.0,3000.0,7.1,2.35,0
Date Movie,Color,Aaron Seltzer,99.0,85.0,64.0,729.0,Carmen Electra,3000.0,48546578.0,Comedy|Romance,...,613.0,English,USA,PG-13,20000000.0,2006.0,869.0,2.7,1.85,806
The Funeral,Color,Abel Ferrara,48.0,99.0,220.0,599.0,Vincent Gallo,812.0,1227324.0,Crime|Drama,...,48.0,English,USA,R,12500000.0,1996.0,787.0,6.6,1.85,344
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Heroes,Color,NaN,75.0,60.0,NaN,833.0,Masi Oka,1000.0,NaN,Drama|Fantasy|Sci-Fi|Thriller,...,379.0,English,USA,TV-14,NaN,NaN,923.0,7.7,16.00,0
Home Movies,Color,NaN,11.0,22.0,NaN,6.0,Ron Lynch,59.0,NaN,Animation|Comedy|Drama,...,82.0,English,USA,TV-PG,NaN,NaN,11.0,8.2,1.33,526
Revolution,Color,NaN,23.0,43.0,NaN,576.0,Tracy Spiridakos,2000.0,NaN,Action|Adventure|Drama|Sci-Fi,...,323.0,English,USA,TV-14,NaN,NaN,821.0,6.7,16.00,17000
Happy Valley,Color,NaN,11.0,58.0,NaN,250.0,James Norton,887.0,NaN,Crime|Drama,...,59.0,English,UK,TV-MA,NaN,NaN,340.0,8.5,16.00,10000
The Following,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000

In [16]:
movie_df.sort_values('director_name', ascending=False)
# 결측치는 방식(오름/내림차순)과 관계없이 마지막에 나온다.

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
Bizarre,Color,Étienne Faure,9.0,98.0,77.0,0.0,Pierre Prieur,19.0,NaN,Drama|Musical|Romance,...,1.0,English,France,Unrated,500000.0,2015.0,0.0,4.3,1.78,114
Sur le seuil,Color,Éric Tessier,9.0,99.0,0.0,6.0,Michel Côté,50.0,NaN,Action|Drama|Horror|Thriller,...,5.0,French,Canada,NaN,3200000.0,2003.0,16.0,6.6,1.85,39
Mambo Italiano,Color,Émile Gaudreault,67.0,92.0,9.0,71.0,Luke Kirby,636.0,6239558.0,Comedy|Drama,...,67.0,English,Canada,R,5000000.0,2003.0,210.0,6.7,1.85,352
The Oxford Murders,Color,Álex de la Iglesia,71.0,104.0,275.0,102.0,Leonor Watling,439.0,3607.0,Crime|Mystery|Thriller,...,94.0,English,Spain,R,10000000.0,2008.0,161.0,6.1,2.35,0
Along the Roadside,Color,Zoran Lisinac,17.0,108.0,0.0,142.0,Brock Baker,431.0,NaN,Comedy|Music|Romance,...,2.0,English,USA,NaN,250000.0,2013.0,297.0,7.1,1.85,231
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Heroes,Color,NaN,75.0,60.0,NaN,833.0,Masi Oka,1000.0,NaN,Drama|Fantasy|Sci-Fi|Thriller,...,379.0,English,USA,TV-14,NaN,NaN,923.0,7.7,16.00,0
Home Movies,Color,NaN,11.0,22.0,NaN,6.0,Ron Lynch,59.0,NaN,Animation|Comedy|Drama,...,82.0,English,USA,TV-PG,NaN,NaN,11.0,8.2,1.33,526
Revolution,Color,NaN,23.0,43.0,NaN,576.0,Tracy Spiridakos,2000.0,NaN,Action|Adventure|Drama|Sci-Fi,...,323.0,English,USA,TV-14,NaN,NaN,821.0,6.7,16.00,17000
Happy Valley,Color,NaN,11.0,58.0,NaN,250.0,James Norton,887.0,NaN,Crime|Drama,...,59.0,English,UK,TV-MA,NaN,NaN,340.0,8.5,16.00,10000
The Following,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000

In [21]:
#duration으로 정렬하고 duration값이 같은 것 끼리는 imdb_score 값으로 정렬 (둘다 오름차순)
movie_df.sort_values(['duration', 'imdb_score'])[['duration', 'imdb_score']].head(20)

                                      duration  imdb_score
movie_title
The Touch                                  7.0         5.2
Shaun the Sheep                            7.0         8.3
Robot Chicken                             11.0         7.8
Vessel                                    14.0         6.2
Wal-Mart: The High Cost of Low Price      20.0         6.8
Sabrina, the Teenage Witch                22.0         6.6
Anger Management                          22.0         6.7
10,000 B.C.                               22.0         7.2
Rules of Engagement                       22.0         7.3
Strangers with Candy                      22.0         8.1
Home Movies                               22.0         8.2
It's Always Sunny in Philadelphia         22.0         8.8
Sonny with a Chance                       23.0         6.1
Star Wars: The Clone Wars                 23.0         7.9
Yu-Gi-Oh! Duel Monsters                   24.0         7.0
Lovesick                                  24.0         7.9
Bewitched                                 25.0         7.6
The Inbetweeners                          25.0         8.4
M*A*S*H                                   25.0         8.4
A Charlie Brown Christmas                 25.0         8.4

In [23]:
# duration: False, imdb_score: True
movie_df.sort_values(['duration', 'imdb_score'], ascending=[False, True])[['duration','imdb_score']]

                                               duration  imdb_score
movie_title
Trapped                                           511.0         8.2
Carlos                                            334.0         7.7
Blood In, Blood Out                               330.0         8.0
Heaven's Gate                                     325.0         6.8
The Legend of Suriyothai                          300.0         6.6
...                                                 ...         ...
Wolf Creek                                          NaN         7.1
Black Water Transit                                 NaN         7.2
Harry Potter and the Deathly Hallows: Part II       NaN         7.5
Destiny                                             NaN         8.1
War & Peace                                         NaN         8.2

[4916 rows x 2 columns]

In [32]:
a=10+20

30

In [34]:
m_df = movie_df[movie_df['duration']>250].sort_values('num_critic_for_reviews')

In [35]:
m_df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
movie_title,,,,,,,,,,,,,,,,,,,,,
The Company,Color,NaN,9.0,286.0,NaN,527.0,Tom Hollander,857.0,NaN,Drama|History|Thriller,...,39.0,English,USA,NaN,NaN,NaN,555.0,7.9,1.78,733
"Blood In, Blood Out",Color,Taylor Hackford,12.0,330.0,138.0,672.0,Jesse Borrego,848.0,4496583.0,Crime|Drama,...,129.0,English,USA,R,35000000.0,1993.0,674.0,8.0,1.66,6000
Trapped,Color,NaN,16.0,511.0,NaN,51.0,Ingvar Eggert Sigurðsson,147.0,NaN,Crime|Drama|Thriller,...,19.0,Icelandic,Iceland,NaN,NaN,NaN,63.0,8.2,16.00,0
Gettysburg,Color,Ron Maxwell,22.0,271.0,33.0,251.0,William Morgan Sheppard,854.0,10769960.0,Drama|History|War,...,256.0,English,USA,PG,25000000.0,1993.0,702.0,7.7,1.85,0
The Legend of Suriyothai,Color,Chatrichalerm Yukol,31.0,300.0,6.0,6.0,Chatchai Plengpanich,7.0,454255.0,Action|Adventure|Drama|History|War,...,47.0,Thai,Thailand,R,400000000.0,2001.0,6.0,6.6,1.85,124
Arn: The Knight Templar,Color,Peter Flinth,34.0,270.0,5.0,292.0,Michael Nyqvist,908.0,NaN,Action|Adventure|Drama|Romance|War,...,54.0,Swedish,Sweden,NaN,25000000.0,2007.0,690.0,6.6,2.35,0
Cleopatra,Color,Joseph L. Mankiewicz,72.0,251.0,311.0,595.0,Richard Burton,940.0,57750000.0,Biography|Drama|History|Romance,...,192.0,English,UK,Approved,31115000.0,1963.0,726.0,7.0,2.20,0
Gods and Generals,Color,Ron Maxwell,84.0,280.0,33.0,67.0,Bruce Boxleitner,789.0,12870569.0,Drama|History|War,...,497.0,English,USA,PG-13,56000000.0,2003.0,640.0,6.3,2.35,953
Das Boot,Color,Wolfgang Petersen,96.0,293.0,249.0,18.0,Martin Semmelrogge,362.0,11433134.0,Adventure|Drama|Thriller|War,...,426.0,German,West Germany,R,14000000.0,1981.0,21.0,8.4,1.85,11000
Heaven's Gate,Color,Michael Cimino,102.0,325.0,517.0,678.0,Sam Waterston,12000.0,1500000.0,Adventure|Drama|Western,...,189.0,English,USA,R,44000000.0,1980.0,849.0,6.8,2.35,1000
Carlos,Color,NaN,108.0,334.0,NaN,30.0,Nora von Waldstätten,897.0,145118.0,Biography|Crime|Drama|Thriller,...,36.0,English,France,Not Rated,NaN,NaN,30.0,7.7,2.35,0
Once Upon a Time in America,Color,Sergio Leone,111.0,251.0,0.0,642.0,Burt Young,22000.0,5300000.0,Crime|Drama,...,495.0,English,Italy,R,30000000.0,1984.0,683.0,8.4,1.85,12000
Apocalypse Now,Color,Francis Ford Coppola,261.0,289.0,0.0,3000.0,Marlon Brando,11000.0,78800000.0,Drama|War,...,983.0,English,USA,R,31500000.0,1979.0,10000.0,8.5,2.35,19000

## flights.csv (항공기 운항 기록)
- MONTH : 비행 월
- DAY : 비행 일
- WEEKDAY : 비행 요일 - 1(월요일)~7(일요일)
- AIRLINE : 항공사 코드
     - UA:	United Air Lines Inc.
     - AA:	American Airlines Inc.
     - US:	US Airways Inc.
     - F9:	Frontier Airlines Inc.
     - B6:	JetBlue Airways
     - OO:	Skywest Airlines Inc.
     - AS:	Alaska Airlines Inc.
     - NK:	Spirit Air Lines
     - WN:	Southwest Airlines Co.
     - DL:	Delta Air Lines Inc.
     - EV:	Atlantic Southeast Airlines
     - HA:	Hawaiian Airlines Inc.
     - MQ:	American Eagle Airlines Inc.
     - VX:	Virgin America
- ORG_AIR : 출발공항
- DEST_AIR : 도착공항
- SCHED_DEP : 출발예정시각
- DEP_DELAY : 출발지연시간(분)
- AIR_TIME : 비행시간(분)
- DIST : 비행거리(마일)
- SCHED_ARR : 도착예정시각
- ARR_DELAY : 도착지연시간(분)
- DIVERTED : 회항여부(1: True, 0: False)
- CANCELLED : 취소여부(1: True, 0: False)

In [36]:
import pandas as pd
import numpy as np

In [38]:
flights = pd.read_csv('data/flights.csv')
flights.shape

(58492, 14)

In [39]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58492 entries, 0 to 58491
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   MONTH      58492 non-null  int64
 1   DAY        58492 non-null  int64
 2   WEEKDAY    58492 non-null  int64
 3   AIRLINE    58492 non-null  object
 4   ORG_AIR    58492 non-null  object
 5   DEST_AIR   58492 non-null  object
 6   SCHED_DEP  58492 non-null  int64
 7   DEP_DELAY  57659 non-null  float64
 8   AIR_TIME   57474 non-null  float64
 9   DIST       58492 non-null  int64
 10  SCHED_ARR  58492 non-null  int64
 11  ARR_DELAY  57474 non-null  float64
 12  DIVERTED   58492 non-null  int64
 13  CANCELLED  58492 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 6.2+ MB

In [42]:
#AIRLINE의 고유값(항공사 코드-범주형)
np.sort(flights['AIRLINE'].unique())

array(['AA', 'AS', 'B6', 'DL', 'EV', 'F9', 'HA', 'MQ', 'NK', 'OO', 'UA',
       'US', 'VX', 'WN'], dtype=object)

In [43]:
flights['AIRLINE'].nunique()

14

In [46]:
flights['AIRLINE'].value_counts().sort_index()

AA     8900
AS      768
B6      543
DL    10601
EV     5858
F9     1317
HA      112
MQ     3471
NK     1516
OO     6588
UA     7792
US     1615
VX      993
WN     8418
Name: AIRLINE, dtype: int64

In [48]:
flights['WEEKDAY'].value_counts().sort_index()

1    8720
2    8535
3    8706
4    8659
5    8453
6    7052
7    8367
Name: WEEKDAY, dtype: int64

In [50]:
flights.head(20)

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
0,1,1,4,WN,LAX,SLC,1625,58.0,94.0,590,1905,65.0,0,0
1,1,1,4,UA,DEN,IAD,823,7.0,154.0,1452,1333,-13.0,0,0
2,1,1,4,MQ,DFW,VPS,1305,36.0,85.0,641,1453,35.0,0,0
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
4,1,1,4,WN,LAX,MCI,1720,48.0,166.0,1363,2225,39.0,0,0
5,1,1,4,UA,IAH,SAN,1450,1.0,178.0,1303,1620,-14.0,0,0
6,1,1,4,AA,DFW,MSY,1250,84.0,64.0,447,1410,83.0,0,0
7,1,1,4,F9,SFO,PHX,1020,-7.0,91.0,651,1315,-6.0,0,0
8,1,1,4,AA,ORD,STL,1845,-5.0,44.0,258,1950,-5.0,0,0
9,1,1,4,UA,IAH,SJC,925,3.0,215.0,1608,1136,-14.0,0,0
10,1,1,4,MQ,DFW,DRO,1335,28.0,104.0,674,1438,28.0,0,0
11,1,1,4,EV,ORD,JAN,1155,6.0,113.0,677,1403,5.0,0,0
12,1,1,4,OO,ORD,MSP,1510,2.0,65.0,334,1646,4.0,0,0
13,1,1,4,EV,ORD,CMH,1010,-2.0,46.0,296,1228,-9.0,0,0
14,1,1,4,UA,IAH,IND,1426,-1.0,102.0,844,1742,-20.0,0,0
15,1,1,4,AA,DEN,DFW,1445,-6.0,93.0,641,1745,4.0,0,0
16,1,1,4,OO,DEN,SGU,1105,21.0,66.0,517,1249,20.0,0,0
17,1,1,4,NK,DEN,DTW,1952,37.0,124.0,1123,31,54.0,0,0
18,1,1,4,MQ,ORD,DAY,2220,19.0,37.0,240,23,20.0,0,0
19,1,1,4,WN,PHX,LAX,1640,51.0,58.0,370,1700,59.0,0,0

In [51]:
flights.tail()

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
58487,12,31,4,AA,SFO,DFW,515,5.0,166.0,1464,1045,-19.0,0,0
58488,12,31,4,F9,LAS,SFO,1910,13.0,71.0,414,2050,4.0,0,0
58489,12,31,4,OO,SFO,SBA,1846,-6.0,46.0,262,1956,-5.0,0,0
58490,12,31,4,WN,MSP,ATL,525,39.0,124.0,907,855,34.0,0,0
58491,12,31,4,OO,SFO,BOI,859,5.0,73.0,522,1146,-1.0,0,0

In [52]:
flights.isnull().sum()

MONTH           0
DAY             0
WEEKDAY         0
AIRLINE         0
ORG_AIR         0
DEST_AIR        0
SCHED_DEP       0
DEP_DELAY     833
AIR_TIME     1018
DIST            0
SCHED_ARR       0
ARR_DELAY    1018
DIVERTED        0
CANCELLED       0
dtype: int64

## 기술통계함수를 이용한 데이터 집계
### 주요 기술통계 함수

|함수|설명|
|-|-|
|sum()|합계|
|mean()|평균|
|median()|중위수|
|quantile()|분위수|
|std()|표준편차|
|var()|분산|
|count()|결측치를 제외한 원소 개수|
|min()|최소값|
|max()|최대값|
|idxmax()|최대값 index|
|idxmin()|최소값 index|
|unique()|고유값|
|nunique()|고유값의 개수|

- DataFrame에 적용할 경우 컬럼별로 계산
- sum(), max(), min(), unique(), nunique(), count()는 문자열에 적용가능
    - 문자열 컬럼의 min/max index를 조회하려면 np.argmax(), np.argmin()을 사용
- 기본적으로 결측치(NA)는 제외하고 처리한다. 
    - 결측치 제외하지 않으려면 skipna=False로 설정

In [61]:
flights['AIRLINE'].sum()

'WNUAMQAAWNUAAAF9AAUAMQEVOOEVUAAAOONKMQWNWNUAOOWNMQOOAAOOWNEVWNUSAAAAOOUSAAAAASOOEVAAOOWNUAUAAAAAAAUSMQOOOODLOOAAVXDLOOWNMQOOAAOOWNOOAAUAWNEVUAMQUAAANKAAAADLMQDLWNMQOOWNWNDLOOAAWNAADLDLWNF9UANKUSAAAAOOEVDLOOMQUSMQEVAAUANKUAUSUSOOWNMQDLDLEVUSAADLAAB6OOMQOOB6AADLDLAAWNAAUAOOEVDLOOOOUAUADLEVUAUAAAEVUSMQUSOODLUSDLDLWNOODLDLAAOODLUAEVDLNKEVOODLEVAADLWNAAOOWNUAAAAAMQDLDLUADLDLWNMQAADLDLUSUAWNEVWNEVUAASEVAAAAUSUSDLEVAADLEVF9MQDLWNOOMQDLDLWNWNEVEVAADLOOUSEVWNVXMQUSWNEVF9EVWNDLEVOODLB6OOASOOVXDLDLUAF9DLDLDLEVEVDLDLOOWNOODLWNUAEVUAUAEVEVUAAAEVUAAAWNWNUAWNUAWNASOOAAWNOOEVUAOOMQDLWNOODLF9EVWNEVWNUAMQOOEVWNWNF9WNWNDLAAWNDLDLAADLAAEVDLMQOOWNOOOOEVMQAAOODLOOUADLOODLDLAAOOAAB6MQMQDLEVUAMQUAMQAAAAWNNKWNAAAAUAWNWNEVDLDLUSWNMQNKOOUSOOEVEVDLWNOOOOUAEVOOEVUSDLUAUAOOUAOOOOAAAAAAEVUSDLF9OOWNUAAAUSOOAAUADLUAASAAWNWNNKAAEVAAAAWNDLUAWNWNDLDLDLEVEVWNVXOOAADLOOWNUAEVUAWNAAWNEVAAAAVXDLNKDLNKEVUADLUAAAEVEVF9DLNKOOOOAAASAANKASWNAADLAAMQEVEVWNUAUAVXEVAAUSDLUAEVUAMQUSUAWNAAUSUSUAWNDLNKF9MQDLMQUSMQWNDLAADLAAUSEVWNAAWNEVASUAMQEVWNEVEVNKDLAANKUAUAUAAAWNMQDLASNKUAAAEVUAMQEVDLAAAADLEVDLWNNKMQDLUAAAUSUAOOEVUADLNKUSDLMQB6B6AAAAOOF9OOUAAAUAUSDLAAUSWNF9USOOUAEVAAOODLWNAAUAEVUSOOUAUSDLEVMQHAEVDLWNUAAADLAAOOASAADLUAUAF9WNF9F9OOMQDLOOOOF9DLDLUAOONKWNAAAAVXNKDLDLAAUSNKUAMQUAAAOOAAWNAAOOUADLEVWNAAUAUAOOMQMQAAVXDLDLDLEVMQUAWNOOUAUAAAOOEVDLDLWNOOEVOOMQDLOODLF9OOUADLWNWNOOOOOOWNDLOOEVWNOODLOOOOEVOOF9UAUADLEVUSOOOOEVAAEVB6EVUAUAUAUAAAVXAADLDLMQOOAAWNMQHAUAEVUSAAUAASUAWNEVMQEVWNEVUSMQUSNKEVWNDLAAOONKDLASF9DLEVASEVAAWNUADLWNDLAAAAMQWNWNOOOOUAB6AAVXUSEVOOAAEVEVDLAAEVMQAADLEVUAMQDLEVEVEVAADLAAAAAAUAEVAAEVWNOOEVEVDLOOEVUSOOWNOOEVEVUAMQAAWNMQUSWNASDLDLDLVXWNAAWNEVWNDLOOASAAEVEVDLVXOOWNAAUAMQDLAAEVDLWNUAEVDLWNAAEVUAUAF9NKOOUAAADLUAMQWNWNMQDLMQEVNKUAWNEVWNAAAAMQEVASWNUAF9EVASAAWNAAMQDLHAEVOOUSOOAAWNWNAANKWNWNEVWNEVDLEVDLUSAANKWNWNUSWNOOWNDLEVWNUADLUSAAAAEVDLMQNKOODLUADLOODLOOUAOOEVAAWNUAWNWNOOWNDLOODLEVDLMQEVDLDLVXUAB6DLAAF9DLAAWNWNAAUSMQWNEVUAEVOOWNAAAAWNUAWNWNMQDLNKAAUAWNOODLAAMQAAEVMQEVEVOOOOF9DLUAAAUAUAOODLWNWNUAWNEVOOOOOODLMQEVWNASMQDLUAOOAAEVUADLAAAAWNNKDLDLEVEVEVEVEVUAUADLUSEVWNWNOOUSOOOOMQDLOOAADLEVWNWNEVAAAAAAOODLWNEVUAHADLUAOOEVVXAAWNEVDLUAEVWNWNWNUSDLAAAADLWNAAUAOOWNWNWNWNWNDLWNDLMQEVMQEVAADLWNVXVXAANKUANKWNDLAAEVDLF9MQDLASAAAADLOODLAAMQWNDLOODLDLWNAAOOWNDLUAAAOODLEVWNDLWNUAUAUSUSAAOOOOWNUAWNAAUSOOOOASWNAAUAMQDLWNNKOOUSWNAAMQOOWNAAUAMQUSUADLF9MQMQUAAADLOOUAB6UADLWNOOWNF9UAUAOOUAEVWNNKDLWNOOVXWNEVEVWNAAEVEVDLUSAADLMQUAAADLNKWNUSWNWNAAUAOOOOEVUADLEVUAAADLAAUAEVDLEVMQUAMQOOWNMQAAAAUAMQAAOOEVAAOOOOUSMQOOAAOOWNAAOOOODLUAAANKWNWNDLAAOOUAF9OOEVEVUAHAAAOOEVEVUSUAWNUADLEVUAOODLDLAAAAWNMQUSUAUSUSASDLUAWNMQUADLUAEVWNVXMQEVEVMQEVWNAAEVOOVXWNEVAADLWNUAAAWNDLDLEVWNUADLEVMQMQUAUAAAWNOOUSMQDLWNOOAAOONKVXDLHADLOOOOOOAAEVUAAAEVUSUAEVEVWNDLB6WNWNUAAAAAUADLVXDLDLWNAAF9OODLUSDLAAWNWNF9OODLWNDLOODLAADLWNNKMQUAUADLWNMQUSUAWNOOEVDLUAUSF9EVAAMQAAUAAAWNUADLDLDLWNWNF9AAMQUAWNWNAAMQDLAAAAEVWNWNF9MQASUAOODLDLOOEVEVDLUSDLMQMQOOEVVXB6MQEVOODLAAUSMQWNUSAAAAWNEVAADLUAUSUSWNWNUAAAUSOOAAMQDLUSEVWNAAOOEVAAMQF9UADLOOUSDLAADLUAWNUSOOWNWNUSWNEVOOUADLOOAAWNUAWNWNDLUAAAWNUADLDLAAOOAADLWNAAUADLASDLMQWNUAAANKAAOOAAUAWNWNUAHAUAAAB6UAUADLOOUSAAUSUAAAAAEVASUAB6WNOOB6USUADLAAOOUAMQEVOOAAAAAAMQDLNKNKEVDLDLDLDLVXDLOOUSF9EVWNUSDLWNAAWNEVVXMQWNOOUSAAWNAAMQWNASWNF9UADLWNWNEVDLWNAADLDLUAEVAADLMQUAEVMQWNWNDLEVWNMQASWNDLDLEVAAWNUAVXDLAAUAWNMQB6DLAAWNAAUADLNKMQOOWNUSUADLUAAAUAAAAAAAB6EVAAUAAAEVDLDLAAOOUSOODLUAWNOOEVEVAAEVDLB6UAUADLWNVXF9EVOOWNOOOOWNDLVXUADLDLOOEVAAEVUADLOOUSUAWNMQOOMQWNAAMQUAUAMQEVMQOOUSNKUSAAUSAADLAADLAAOODLUSOOEVF9ASOOUSAAUAOOEVUSUSEVWNUSAAF9NKEVWNOODLAAUSMQWNDLWNUAUSAAF9F9AAMQWNMQWNWNOOUAMQASUAMQOOUSMQOOAAUAUAWNOOOODLB6EVAAAAWNVXAAF9UAWNASOOWNOOMQUAOOOOWNWNWNUSAAMQEVWNASMQDLWNF9EVEVOOUAUAWNAAUAWNWNAAWNUAUAEVDLAAUAMQWNUADLDLDLOOOOOODLMQWNDLUANKHADLUAAAUAOODLOOEVMQDLMQDLAADLMQMQDLDLAAAADLAADLEVDLMQAAASMQAADLAAOOEVUAOOAADLDLUSUSOOAAAAUAOOMQUSUAEVOODLMQEVWNEVASUAWNWNF9OODLAAWNVXEVUSEVWNDLAADLUSB6MQOODLNKAAMQOOOONKOOAAEVAAWNAAAAOOVXUAUAUSDLF9UADLEVAAWNMQDLDLOOUADLUSEVWNEVWNAADLEVEVAADLAAOOAAOOAANKWNMQAAAAMQOODLB6UAAAUAMQEVEVDLWNMQEVWNASAAUAWNF9OOUSDLAAOOOOMQUAWNUAUANKEVAAMQEVOOUADLDLWNF9AAWNAAWNUAOODLUAMQWNUSVXUAEVEVOOWNMQDLOODLUAMQMQEVMQUSUADLUSDLNKF9AANKEVWNOOAAOOUAF9MQWNDLDLOODLWNDLOOWNDLUAOOAAEVWNAADLAAUSEVAAEVAAUAUSWNDLDLMQAAAAF9WNDLAAEVUAAANKUAEVUAUADLNKF9USEVDLDLUAMQEVUSUAUADLWNWNWNDLOOOOAADLDLWNAAMQNKOOASAAWNMQMQOOUAMQUADLUSUAWNOOOODLUSAAAAAAOOOOWNAAEVOONKMQAAWNAAAAUAOOUSDLOODLEVUADLDLAAUAWNNKMQAAOODLAAEVMQEVOOOODLF9AAAAOOAAOONKWNUAAAOOVXVXOOAADLDLEVWNWNWNAAEVWNAAAAMQAAWNUAOOWNAADLUAOONKUAAADLWNWNEVB6DLB6EVDLB6UADLDLAAAAUAWNOODLUADLDLASVXEVEVUAMQEVUSMQUSAAUAWNAADLEVMQOODLDLDLMQWNWNDLAAAAEVUAAANKWNEVVXOOWNWNUADLMQMQAAUSMQWNDLEVHAEVOOAAUAOODLAAVXMQAADLUAAAB6WNEVDLNKF9UADLOOWNWNDLDLWNMQDLWNEVOOEVWNUAWNUAMQEVAADLUAOODLWNDLMQUADLOODLAAOOWNMQUAWNAAEVUAUANKDLAADLOOEVDLB6MQUADLWNUAMQMQAAUAWNWNDLMQOOWNEVUADLOOF9WNDLWNUADLWNDLWNAAMQMQOOEVWNEVOODLUSNKNKAAAAWNUAAAOOEVEVB6WNWNDLDLWNOOUSUAAAUAAAASNKAAOOWNOOOOWNWNEVAAWNWNUAMQOOUAUAAAMQOODLUADLDLUAOOMQEVEVDLWNDLDLOOWNEVMQVXEVDLDLMQDLAAMQUADLAADLWNWNUSEVUAEVWNEVDLAADLAAUADLDLOOUAAAAAF9WNEVOOWNUSEVUANKAAAAASEVUSWNMQUADLDLUSOOMQNKEVDLOODLDLUADLMQAAAAWNOODLDLDLUSMQEVOOF9AAWNWNWNMQDLUAAAUAUAUAWNUAAAVXDLEVUAASWNOOF9AAWNEVAAAADLASUAUAUSWNUANKOODLWNOODLDLOOF9DLDLUSEVDLAAB6UAUAOODLUANKUAAAOOAAWNOOVXDLUSMQMQOODLDLDLOOMQAAAAUAUSAAAAOOOONKMQUSAANKHAOOVXDLOODLB6WNWNEVWNWNDLDLMQDLEVDLDLOOAADLDLOOUADLMQUAEVDLEVUSUAUAAAAAEVHAUAF9EVUAWNAAEVWNDLWNB6F9EVEVWNAAWNOOOOWNUAAAUAOOAAUSF9MQDLDLWNWNDLOOOOWNUSAAMQB6UAMQUAAAEVDLUSWNEVF9DLF9UAVXEVWNAADLNKUAUAAAUAWNOOUAMQNKWNOONKVXUAEVDLMQEVOOMQUAUAAANKNKOODLEVWNNKWNDLDLDLDLAAOOAAWNDLB6OOMQWNAANKMQOOWNDLDLAAAAOOAADLUAMQDLB6AAAAWNOOF9AAUAVXDLUAUSDLAAUSAAUAEVMQUSWNAAUAOOWNWNAADLDLUSDLAAMQAAMQMQOOEVEVDLAAWNUSMQEVMQMQOOWNDLEVUADLF9EVMQDLUAWNWNWNF9WNWNDLOODLUAUSWNWNDLDLWNEVNKEVDLDLEVVXUADLAAB6AANKDLUAOOUAWNWNDLAAOOUSOOVXUAWNUAAADLWNWNMQUAUSUAWNUADLMQOOOOMQUAOOVXAAOOAAMQDLOOUAMQDLAAAADLOOOOOOAAB6USDLEVDLASDLMQOOUAMQWNUAAAUADLUSDLDLAAWNEVUAAAEVMQUSAAOOMQUSUAUADLOOOOUAOOWNWNDLMQUAWNEVWNDLWNDLUADLUSDLDLEVWNUAEVAAUSAAUAWNAAOOAAHAAAMQUADLUAAAUAWNWNMQWNAADLOOOONKEVEVWNWNEVF9OOEVWNAAOOUSUAOODLOOAADLAAOOOOEVUADLMQUAMQWNEVDLMQAAMQMQUAUAOOEVDLDLDLB6NKOOMQWNNKMQUADLWNOODLNKWNAAEVUSAAOOWNDLUADLEVEVDLOOOOUADLUSUSWNWNUAAAWNDLUAWNDLAAWNOOMQEVDLWNWNEVVXVXASEVUAOOWNAAAADLVXUAUSEVWNASWNDLAAMQWNOOAAOOAAMQEVDLEVUAMQDLDLMQUAAAAAUAEVEVEVNKOONKEVMQEVUSOOEVOOEVUADLWNHAUSMQAAAAWNASUAEVNKEVASEVMQDLUSDLEVEVDLEVMQOOWNAAUAOOEVWNUSOOEVUAUAUADLAAUAEVUAUAOOMQMQWNVXDLAAWNDLUAWNOOOOUAUADLOOUAAAWNOOHAUSEVDLEVAAAAUAEVDLDLWNAADLF9UAOODLAAVXUSNKDLDLWNOOMQOOWNUSAAUAWNDLVXWNWNAADLAADLDLAAAAUADLEVDLDLWNWNMQOOAAMQEVOODLWNUSAAF9EVUSUAOOUSAAAADLAAUSUAUAEVVXEVUAEVB6USEVAAAAAAMQWNUANKOOOOUAWNDLMQWNDLAAEVUAOOOOAAEVUSAAOOUADLOOOOEVMQDLMQDLWNOOOOOOOOWNUSUSEVUAAAUAUAEVDLAAUSEVDLAAEVDLWNAADLWNDLAADLOODLF9OODLDLUSAAMQNKF9AAWNUAWNEVUAWNOOOOOODLUAF9WNDLWNWNOODLWNEVWNEVDLMQMQEVMQUAWNASDLAAOOAAF9DLAAOOAAUSAAOODLVXUSUAOOEVWNMQWNNKDLAAAAUAAAEVDLEVOOOOUAAAAAMQEVOOUSUAUSUADLOOEVWNDLAAUAUAEVAAEVAADLUAWNUSDLDLMQWNMQEVOODLDLUADLASEVDLWNMQDLUADLMQUAEVASEVMQWNDLOOUSVXAADLWNOOUAUAOOAAVXDLDLEVAAEVAAUADLEVOOUAOOWNAAUAWNDLEVMQWNEVAADLEVUSWNMQDLOODLMQUSUAMQUSEVAAUSDLDLWNMQMQOOF9WNEVMQUAOOUAEVUAWNOONKWNOOMQF9UAWNAAWNF9UAOOOOEVWNUSOOWNAADLAADLEVMQAAMQEVAAMQDLASOONKUADLOOAAEVOOMQUSDLUSMQUAUADLWNUAEVDLWNOOEVOOOOWNUAWNUADLWNF9EVAAAAUAUAMQEVUSOOF9OOEVUADLDLDLUADLWNB6EVOOOOOOOOUADLMQAAMQWNEVOOUAWNVXEVMQAAAAAAEVWNDLUSNKUADLOOASEVVXUAAADLOOEVDLOOAADLUSUAWNWNVXDLNKOOAAWNWNNKAAOOOOMQWNDLNKUAUSAADLUADLMQF9AAAAOOMQEVUADLEVAAEVAAEVWNDLVXWNOOASF9AAEVWNAADLEVEVDLAAOOUAUAUSDLEVOOWNDLUSAAEVMQWNWNUADLUADLAAUAEVMQUAAAUSWNAAUAAAUAWNF9AAMQEVAAMQUAAADLUSDLDLUAUSEVUSB6AAUAUAUAUSWNOOOODLAAMQUAWNWNDLDLWNAAAAUAMQAAAAMQDLWNOODLDLDLOOEVEVWNEVDLOOUAUAUAWNWNMQEVWNDLNKEVWNF9DLUSAAOOOOWNUAUSOOWNOOUSUAUAMQAAVXWNAAAAOOUADLOOUAMQEVUSDLAAMQOOUSNKDLWNDLEVAADLAAWNEVDLUADLUAASDLDLNKAADLMQAAWNAAUADLDLAAUSUAMQDLWNASWNMQEVWNEVAAMQUSMQDLDLDLF9USWNDLOOOOAAUAAADLDLNKWNOOASVXUSUADLEVUAOOAAUSUAWNAAWNWNNKAAUSOOEVMQUSDLMQAAF9USMQUSMQOOVXOODLDLDLDLAANKMQF9DLDLWNOOUAB6DLUSOOEVUSASUSAAOOUADLAAEVEVDLDLDLUAUAEVUAVXAAOOUADLEVOOUAUADLOOF9OOWNAAUAEVEVDLWNWNWNAAAAVXOOF9OOWNWNVXUAWNEVAAAAMQEVUAUSDLF9DLDLEVDLEVEVDLOOEVVXOODLEVEVDLWNEVOOUSUAUSAAF9DLDLMQNKAAWNMQDLAAAAUAEVWNMQOODLEVOOVXWNEVAAEVDLMQOOAAAAWNASOOUAWNDLUAWNOOOODLAADLF9NKMQEVAADLMQEVAAUAUAUAEVDLUAUSDLASMQOOAAUAAAMQWNAAUAMQMQEVDLEVWNDLOODLEVWNMQWNF9WNAAWNDLAAAAWNDLOOOOAAAAWNUADLEVOOWNOOOOF9WNAAUADLDLOODLAAAAUAWNDLEVDLOOOODLUAWNNKOOUAWNOOOOAAWNDLWNOOWNOOUAEVAADLDLOOOOWNOODLWNAADLDLWNAAAADLUAMQWNWNUAUADLUAUSOODLDLEVNKDLDLDLUSEVEVUAMQEVWNUSDLDLUAMQUAEVUAUAWNDLWNWNUSEVDLAAEVEVEVWNMQDLVXDLAADLEVWNOOAADLAAEVWNDLUADLDLUAF9UAAAUAUSAAWNEVAADLOODLAAEVAAWNUAWNDLAAWNDLNKUSEVOODLWNDLOOOOOOOOUAWNOOUANKEVASUAWNDLEVDLUSUAMQWNDLWNEVUAUAWNWNMQDLAADLB6UAWNEVVXOOOOMQAAF9AAUSHADLWNUAOOWNMQDLAAUAUSUSF9EVDLMQOOOOWNAADLOOEVEVEVUAWNOODLEVEVDLMQWNAADLOOUSASWNEVWNWNAAAAWNAAAAAAWNWNOOMQEVOOHAUAEVWNEVMQF9DLDLUAUAWNUAMQAADLWNMQASUAAADLDLMQUADLNKAAAADLEVMQWNEVUAEVEVDLWNMQWNOOWNDLDLWNWNUSWNMQUADLMQUAWNF9DLWNEVUSDLWNUSWNOOMQAAUAEVMQUSUAUADLOOUAOODLNKOOAAEVAAUAUSWNNKWNEVDLAAWNMQUADLMQDLOODLUSAAAAAAEVUAUADLWNOOUAWNWNEVWNDLAAUAVXUAOOOOWNVXDLDLDLVXDLF9DLUADLAAWNUSOOUAOOB6OOEVDLDLOOOODLMQWNEVWNMQWNAAAADLUSMQMQDLWNUSAAUAAAB6OOMQDLUAWNAAEVUAASOOWNOOWNMQMQNKUAMQEVUAAAWNWNMQMQNKEVMQMQWNDLUADLUSDLAAUSWNUAMQWNDLWNDLEVOOOODLOOEVOOAAEVUSUSMQDLEVUAAAB6UAF9DLNKAAAADLUAAAEVWNUAWNDLMQOOUAEVAAEVUSEVOONKDLMQUAWNWNEVAAF9WNDLAAWNAAEVDLDLUAUSDLWNOOUSDLWNWNDLMQEVVXOOUADLEVEVOOEVWNWNMQAANKMQEVDLWNDLUAWNVXDLAAAAWNAAMQDLF9AAAADLAAEVF9EVVXAAOOEVDLUSUAOOUADLEVAAUADLWNASDLDLVXDLAAOODLOODLEVMQOOMQEVEVUAAAUAUADLEVAAWNAADLNKEVOODLOOOOWNAAOONKB6UAWNAAAAUSUSAAUADLMQAAWNDLDLDLUAWNDLDLASDLDLDLUAUAOODLAADLDLDLWNDLMQOOOOEVAAOOUAB6AAUADLUSVXDLDLEVDLMQEVUADLWNWNWNUSUAUAWNASEVWNAADLWNWNWNEVASAAMQF9UADLVXWNMQWNVXMQDLDLUAUADLUAWNVXDLDLOOOODLAAVXAAMQAAMQDLDLMQOOB6OODLEVOOVXWNWNWNWNEVUSEVEVWNOOVXEVUAOOOOUAAANKUSMQUSASDLAAUAWNUAUSOONKWNEVMQAAMQHAOOVXOOAAUSOOAAWNUAEVWNDLWNUSF9WNOOAAMQEVUSWNWNDLUAMQOOOODLAAUAMQEVAAEVEVDLAAWNWNOOMQDLEVEVUAWNDLWNNKMQAADLDLDLWNDLAAMQDLASUAUSDLEVUSMQVXUSNKUAF9MQOOWNDLUSNKEVDLUSAAWNAAOOMQOOAAUAMQF9OOAADLDLDLUAAADLAAF9NKMQMQAAAAAAWNDLB6UAEVWNUSAADLUAAAMQDLDLWNMQAADLUSOOMQAAAAUAWNOOUAWNWNAAWNAADLWNDLWNWNOOF9UAWNVXDLDLVXF9OOOOAAAADLDLAAEVEVAAEVOOUAAADLDLEVNKWNASUSUAOOF9AAUAWNAAWNNKOOWNF9UAOOVXOODLUAOOUAUAWNWNMQB6AAWNDLWNOOB6EVUSMQUAUADLWNOOUAOOWNVXEVEVUAAADLEVDLMQNKDLASAAWNEVDLOOMQOODLWNEVUAUAVXAAMQOOUSEVNKAAF9ASEVAADLDLDLUAEVWNUAMQHAAADLAADLAAWNEVDLF9AADLUAWNOODLAADLB6VXMQMQOOUAB6DLUAAAWNMQDLMQDLWNWNDLF9DLAAWNAAB6WNWNDLEVEVWNNKUSOOWNDLEVDLOOUAAAVXUAUAWNWNAAOOOOAAASAAAAWNWNDLB6ASAAWNMQVXDLUAWNOOUSWNWNAAUAAAMQAAWNDLMQHAAAUAUAOOUSDLAAEVDLUAUADLWNOOUAASOOWNOODLAAWNOOUAAAUADLAADLWNUAWNUAWNDLAAMQNKHAAADLUAAAWNDLEVAAWNDLWNAAAAOOAAMQMQOOUSF9MQUADLWNUSOOUSWNMQWNB6EVUSAANKASOOWNEVWNWNEVHADLAAEVF9MQAAWNDLASMQAAEVUAWNDLVXUAUADLVXEVDLUAWNWNUAEVAAAAEVNKUAWNWNAAAAUSWNEVDLDLF9UAUSUSUADLUADLVXDLWNWNNKDLOOOOUADLWNUAEVAAMQEVOOWNDLMQWNF9WNDLAAMQF9WNUAEVDLF9AAUADLEVAAEVAADLUADLWNUSUAMQEVOOOOOOOOF9MQWNUSMQDLUAEVMQWNUADLWNDLDLEVDLOODLB6AAUSAADLF9DLWNAAUSAAWNDLASAAUSAAUAOOVXNKAAUAUSOOAAMQMQEVVXEVOODLWNDLAAWNWNUAVXDLOODLWNUAAAAAMQDLDLEVDLOOOOUAWNEVF9DLWNUAWNDLDLWNWNDLWNAAMQWNAAEVAAEVEVEVWNOOOOEVUSDLAAUAUAOOOOUADLOOAANKDLB6WNNKWNDLNKVXNKB6MQDLVXUAUAEVWNUAEVDLAAUAF9MQOOOOAAUSMQWNAAAAUAMQUAAADLAAMQNKAAMQMQWNF9OOOOOODLDLVXWNDLEVDLAAWNOODLWNDLMQWNOOUAUAAAWNWNOODLAAOOUSWNOOMQDLAAOOMQWNUAAAMQAAUSUAOOOOWNASMQOODLEVDLEVDLWNWNDLEVUAEVWNOOAAAAASF9OOASWNAAMQUADLUADLAAEVDLUSOOOOOOMQVXOONKOOAAAAUAAAMQAAWNDLMQMQUAAAAAWNEVDLUADLWNUSAAAAUAAAUAUAMQDLUAAAEVMQOOEVOOEVDLWNOOAAWNEVOODLEVMQAADLUAWNDLDLOOOOUAUSDLDLOOMQUAOOAAWNMQAAAAMQEVB6WNDLAAVXOOUAUSAADLAADLUAOOWNWNWNEVAAVXAAWNAAF9NKAAWNAADLDLWNOOEVWNDLDLUAAAUAOOWNEVAAWNOOUAEVDLDLMQWNUAWNDLOOUSUSDLAAEVOOAAUAOOUSUSDLUSWNUAAAOOWNVXAANKUAUANKDLUAMQAAAADLDLAAUAWNEVAAEVOOWNEVAADLOOUAUAASWNWNWNUAMQWNWNDLUAEVEVWNAADLDLUSWNVXOOUAAAOOOOEVWNUAAAWNWNMQEVMQUAOODLOOEVOODLDLUAOOAAAAWNEVNKDLUSF9OOEVDLDLDLMQAAOOF9NKOOOOOODLDLOOMQWNOOAAUSOOEVDLOODLDLOOB6EVUSAAAAEVMQEVEVMQDLWNMQOOUAAADLWNUADLASWNWNAADLWNF9WNAAAAUADLWNDLAAWNWNOOUADLAAAAUADLMQUSOODLEVUAWNF9AAAAOOUADLUAUAWNASDLUADLMQOODLAAAAAAOOOOOOOOOOWNWNDLUADLDLOOOOEVOODLWNMQDLOOWNEVOOUAOOWNOOWNAAOOOOUSAAUSWNEVAADLNKWNMQF9EVVXF9UAMQWNOOOOUAOONKASOOAAAAMQDLAAMQDLEVUAWNAAMQUSF9OOAAVXWNDLUSDLAAAAAAAAUAUAOOWNUAOOAAAAEVUADLOOOOWNEVWNASDLMQWNB6AANKNKEVWNDLDLEVUADLDLEVDLDLUAF9UADLDLAAAAUSAAMQB6NKVXUAVXAAWNWNMQMQAADLWNAANKUSDLDLDLUAMQDLDLOOOOAADLEVMQWNUAUADLAAAADLWNDLWNOOOOUAWNOOOOUADLF9DLOODLMQMQUAAADLVXUSAAAAMQAADLAAUSAAOOWNDLUADLOODLWNMQAAAAUSDLWNDLMQWNOODLWNDLEVDLUSNKEVUSAAASOOEVDLAAWNUADLDLWNASWNMQWNWNUAOOOODLAAWNWNWNDLMQDLAAOOOOAAOODLAAMQDLEVOOOOMQDLDLEVWNAAAAMQWNDLWNWNAADLUSMQEVDLEVOODLAADLUADLOONKDLDLEVF9EVMQUSEVUSDLAAUANKWNUSUAAAUSDLEVAAUAEVOOUAUSEVWNWNAAEVDLAAUSAADLAAUSAAOOUADLNKOOUAMQUADLEVWNDLWNUAUAUAMQDLDLAAUSDLAADLDLVXWNWNWNDLAAUAUAUAMQUAUAAAWNOOWNAAMQOOASWNOOMQWNEVWNOOAAOOOOEVEVWNDLAAMQMQMQDLWNDLUAOODLB6UAUANKEVOODLAADLDLEVOOAAF9AAAAVXAAWNWNDLDLDLOOUAEVEVNKWNOODLWNAAF9WNWNEVWNOOEVVXOOVXAAEVMQEVEVUAAAMQOOMQUAWNWNOOAAUADLMQUADLDLAAEVEVEVEVOOF9WNDLMQEVDLOONKUSAADLUAAAUAWNAAAAMQEVAAAAUAUSAAAAWNUAWNWNDLDLWNAAWNDLEVAADLUAWNWNASOODLDLAAUAWNWNWNMQDLUSUADLAAUAOOAAAAOOEVNKWNDLWNUANKOOAAEVEVMQDLEVDLUAUAOOUAWNDLOOMQUAOOAAUAMQWNOOAAOOAAEVMQUAWNEVEVUAWNUSOOWNWNUAEVOOEVAADLF9USAAF9WNOOMQUSAAAAEVMQUAMQWNUAAADLOODLMQMQAADLUAWNEVDLUAAAOOVXUAOOVXUADLMQEVAADLWNWNAAOOOOUAUSWNAAOOUAOOOOMQOOUAUAWNOOEVEVDLOONKWNWNWNOODLWNDLDLDLOOMQUAUADLUAF9EVUAUSUAUAUAAAAADLUAWNAAMQNKVXWNWNDLMQUAOOEVWNEVOOUADLUAOODLDLMQVXOOAAEVVXWNUSAAEVWNWNNKUAOODLEVWNF9UAAAUSDLWNMQWNAAOOWNUAWNDLWNUSUSDLDLUSMQWNOOAAVXOOOOUSF9EVDLEVEVAAMQUAAAOOUAEVMQOOAAAAEVMQDLWNDLUSWNMQUAWNWNWNEVVXWNUAOOEVDLOOOOWNAANKUADLUADLOODLUAEVMQWNNKEVAAMQWNDLAAUSASUAMQUAWNDLAAAAASEVUSWNOODLDLUAEVOOWNAAOOEVMQUAVXOODLDLDLEVWNF9WNEVDLDLAAUSDLUSOOUADLUAAAASOOOODLDLVXDLDLEVEVOOWNDLOOMQWNEVWNUAUSOOEVEVNKEVDLEVEVWNEVDLDLWNMQAAAANKOOMQVXB6MQUAOOF9DLAAEVUSWNDLDLWNOOUSUAOOOODLDLWNAAEVUAOOEVDLF9UAOOUAEVDLDLWNOOUAWNWNWNUADLMQDLASUADLMQMQDLDLB6WNDLEVEVMQMQAAEVDLUAOOAAUAAAUAWNUSDLMQAAUAMQDLDLB6AAEVEVDLDLAAUAF9DLWNASWNWNUSUAAADLDLEVAAWNOOUAUADLOOAANKVXMQAAWNMQNKWNF9WNWNAAWNDLWNMQAAOOEVWNF9EVDLAADLUAEVDLMQAAOODLUAUAF9DLEVOODLDLUAAAEVEVEVAAF9DLUAEVEVDLVXAAUAWNUAAAUAWNASWNVXVXUAEVEVOOUADLWNUAOOAAEVWNUADLEVAAEVAAOOUADLDLAAUSDLUADLUAUAUADLDLOOEVMQEVAAEVMQWNWNUAMQUSEVAAUAUSUSDLDLOOAADLUAWNUSDLDLDLAAOOWNWNUAOOAAMQOOUAWNUAUAUSAADLAADLEVVXOOASDLUSASUSWNWNWNDLUSAAEVUAAADLAADLEVDLEVDLEVOODLUAMQUANKUAAAOOWNDLMQOOWNAADLUADLUAOONKWNOOUSASDLDLUAWNMQOOUAWNEVUSUAAAAAEVWNOOUAEVWNUSEVOOAADLEVWNEVMQASDLDLEVOOEVVXF9DLOOASUAOOAADLUSWNOOAADLMQUAMQUSUADLMQAADLAAAAOOF9UAEVOOWNDLEVMQEVDLHAUADLEVDLOOAAOOMQUAUAUAAAUSAANKAAVXAADLWNUAWNMQMQUADLMQVXWNMQOODLAAF9WNEVDLMQDLMQAADLDLMQOOEVUAEVNKWNWNAAUAMQMQWNMQOOEVOOOOWNAAWNOOOOMQWNUAOOEVEVOOUADLAAAAEVOOAAAADLUAOOWNF9NKUAOOOOAAUAEVWNUAOOEVMQDLAAOOWNAAF9HAOOAAUAEVMQWNEVDLEVAAUAEVDLWNDLWNASAAAAMQWNEVOOUAEVOOUSUSOOOOUAAAUAWNAADLAAUSEVAAUAAAAANKUAMQAAUAAAF9EVDLOOWNDLOOAAEVDLEVDLOOEVOOOOUAUSOOEVDLUAUAUSF9EVWNMQDLUAOOUAEVUSWNDLOOWNOOOOAADLDLUSOOAAWNAADLEVEVOOVXDLOOWNASAAOOWNEVAADLUAMQOODLDLDLUADLDLDLASOOUAMQOOOOMQASEVAAAAOOOOOOEVOODLWNWNUAUAAADLAAOODLEVEVDLDLWNWNEVASASEVAAOOUSOOAAUAOOWNAAWNUSUAUAOOOOOOEVOOUSDLAAUAAAMQAAOOUAWNDLEVAAOOWNAAMQAAMQDLOOUSUAWNUAWNUSWNAAVXEVOOAAOOVXWNDLOOAAUSDLWNEVVXAAUAAAF9DLEVUSASDLAAEVDLWNMQDLWNF9DLEVOOOOUSWNF9UAOOAADLMQWNDLOODLEVDLDLAADLUADLDLUAUSWNOOASUAUAAAUADLAAWNWNWNOOAAWNDLEVUAAAUAEVOOUADLWNUANKVXOOAAAAOODLVXOOUAWNUSOOOONKWNDLDLDLUAWNUADLWNEVAADLDLMQUAOOOOWNWNDLWNDLVXUSWNDLDLWNWNAAAAUAAAAANKUSOOOOAAOOUAEVDLUAAAUSMQUSOOEVUADLWNF9WNOOMQUAWNNKWNUSWNDLAAOOWNHADLUAWNDLUSDLDLEVNKMQWNWNWNUAEVWNUSMQASDLUAEVDLDLMQUAVXUAF9USUAVXWNUADLWNVXUSWNWNUADLDLUSWNUSWNB6OODLUAUAWNB6USOOAAVXAAEVWNDLNKHAMQDLUAUAEVUAF9F9MQAAWNAAMQUADLDLUSDLWNMQNKUAUAMQDLMQWNUADLUSF9WNEVOOAAOOWNWNDLUAUAEVDLOOB6OOWNWNWNEVMQUAOOOOWNUSAAOODLUAAAF9DLEVDLWNAAAAB6UAWNWNDLOONKOOEVUSUADLF9OOUAAAMQDLF9DLAADLEVDLOOAAUAB6WNF9DLUAMQAAEVDLEVDLNKDLOOWNMQWNOOUAUAMQWNUAMQUSUADLOOUSAAUAOODLEVUAOOWNMQDLWNUAUSVXDLAAWNMQDLDLEVDLEVUSMQOOAAEVUSAAWNVXUSAAAAWNOOF9UAMQUSDLUAEVEVWNOONKUAWNAAOOEVUAAAWNDLMQDLWNUAOOMQWNOOEVUSWNOOEVWNAAEVUAASDLAAWNUAUAAAUAWNWNDLUAMQDLOOOOUADLEVWNWNUAEVB6AADLMQUADLF9OOUAMQEVUAOOUAWNUSWNDLWNEVUAUSUAMQUAUAUAAAUAUAAAF9OOMQOODLDLEVOOEVWNMQOOEVDLEVWNDLEVWNMQUSB6DLUAAADLDLDLDLWNB6DLUAWNOOAAEVWNUSAAAAEVDLMQEVUANKWNAAUSAAOOWNDLUSAAAAB6EVUAOOMQUSEVUAAANKWNNKDLUAAAOOUAEVUAMQWNOOEVDLDLUAMQB6AAUSEVDLAADLWNEVDLWNOOOODLEVEVAANKDLOODLDLEVDLMQUSWNF9MQWNVXF9B6USWNOOAADLUAAAEVUADLEVUAUAWNDLDLMQEVDLDLOOWNWNOOUANKUAAAOOUAASUAWNNKDLWNEVWNDLAAAAWNDLDLUAOODLWNDLEVUAUAWNUAEVWNUAUAAAEVUSUSWNWNEVWNASOOEVMQUSDLWNWNUSOOMQOODLASUAWNEVDLUSOOUAAAWNMQAANKUSDLAADLWNEVASMQWNWNAAUAAAAAAADLOOEVOOEVDLWNDLWNAAEVUAASAADLEVWNDLNKNKWNAAEVOOWNWNDLAAEVDLAAUAOOOODLMQDLDLOOUSAANKAAF9USUAUAWNDLUADLUAEVOODLUAMQVXEVOOUADLUSWNUADLUAOOUAWNEVAAEVEVAAAAMQMQWNB6DLF9OODLMQUAUADLDLUSDLAAF9UAWNMQEVUAUAMQUSOOOOOOWNOOF9DLWNAAOOOOEVNKWNUAAADLWNOOAAOOAAUAUAAAOOUAOOOONKEVUADLAAUAWNWNEVUADLOOAADLWNVXUSUADLMQEVOOF9DLMQAADLAAMQWNDLUAAADLUAEVUADLUANKNKWNOOAADLMQUAEVEVNKWNUSWNDLAANKEVDLOODLEVAAOOUAMQUAWNDLDLDLASEVUAEVNKUAEVAAWNEVF9WNDLEVDLOOOODLDLUSAADLB6DLWNDLDLWNDLDLUAUAWNDLEVNKOOWNMQEVUSUSAAEVEVDLDLDLDLUADLOOEVOOWNUAB6WNB6AAOOUSUAAAOOMQUSUSWNWNOOAAWNB6DLEVMQUSDLEVAAUAOOAAAAAAAAUAUAEVAADLDLAAUADLMQUSWNDLOODLUAUAEVUSWNUAEVOONKEVWNMQUAMQDLOODLDLEVEVDLEVDLASDLEVUSMQOOWNEVAAMQDLWNAAVXMQAADLMQMQWNUSDLUAOOEVUAWNUADLWNOOAADLDLDLUSAADLMQOOEVOODLWNDLDLOOEVEVMQDLDLWNOOWNEVWNUAAAUAWNWNWNAAEVOOAADLAAWNDLOOWNDLEVUANKUADLAAUADLMQDLDLDLEVF9DLAAF9MQEVWNAADLDLAAEVDLWNDLOOEVEVWNWNWNOOOODLDLEVAAVXWNDLOODLOOUSEVB6UAUAUAUAEVDLOOEVEVAAWNOOMQWNASDLEVUAOODLAAOOUSAAUAUAVXAAMQF9F9F9OOAAEVUSWNEVAAEVAAOOMQDLWNDLASF9DLOOUSDLAAUSUAOOEVDLAAUAMQUSMQDLWNAAUAWNWNOOUAOODLUSAAOOEVOODLWNUAMQEVEVDLOOASOOOOOOOOAAVXMQAAB6EVWNWNOODLWNWNMQEVUAOOOOUSAAWNAAOOUSUAUAAAMQEVWNOOEVEVNKUAOOAAUAUAMQDLMQWNMQUANKWNEVEVWNEVOOUSMQAAOOAAUAWNUAAADLEVOOWNAAVXEVAAVXAADLMQDLOOWNAAUAUAOODLUAUAUADLVXDLEVAAB6NKDLAAAAOOAAUAOOWNNKWNDLWNF9ASWNDLAADLOODLUAWNEVMQMQWNUSEVUAWNDLNKEVWNUSAAWNWNOOUADLUADLF9EVDLUAOOUAUAWNDLWNDLDLDLEVWNNKOODLASWNASOOEVOOVXDLAAAAOOUSAAUADLEVDLAAMQOODLUAEVAAAAWNWNAAEVEVWNWNOODLDLOOUSDLUANKEVWNMQWNUAWNOONKEVDLUSOOVXUSUADLDLUSOOUAWNOOWNMQDLDLOODLDLOOMQDLOOWNOOOODLAADLDLUAWNVXVXWNNKDLDLOOWNAAUAUAAAUAUSAAOOUSDLASDLDLEVAAEVAAWNUAOOASOOWNDLDLDLAADLB6MQWNNKAADLDLUAAAMQEVOOEVOOAAWNUAEVAAMQOOAAOOUSWNUAOOAAWNWNDLAAMQEVDLOOWNEVDLAAUADLNKAAOODLEVUSUSWNEVF9UAMQOODLVXDLEVUAUSUSOOUAWNWNUAMQOODLMQASWNUAEVAAAAOONKEVB6UAAAEVNKDLEVOOWNWNWNDLUAAAOOAADLAANKWNUAWNUAWNOOAAF9AADLEVWNWNWNUAAAUAWNEVUAUSEVWNUAUSUAMQAADLMQEVDLDLAAEVMQF9WNDLOOMQDLWNMQDLUANKF9USUSUAEVWNDLWNMQOOAADLOOUSMQWNUSAADLDLDLDLOOAAOOUAVXDLDLDLUAWNDLOOOONKB6DLAADLOOMQOODLMQDLUAMQMQDLMQUSEVDLUADLEVDLWNDLDLEVDLWNWNUADLEVWNMQVXDLVXWNUADLAAAAWNDLDLAAUAWNWNUAWNOOOOOOOODLDLAAWNEVEVDLOOUSUSF9WNAANKDLUAMQUAWNAAWNAAWNEVOOOOUAAAMQOOHAAAOOUAMQUAUAUAEVUAAAB6EVWNAAUAUAAAOOOOWNAAMQAAAAAAUAOOVXB6OOUAOOWNOOVXAAMQOOAAASWNUAOODLUAUAF9WNAAWNAAUAUAAAUAAADLF9WNMQUAOOAAAAEVAAEVWNNKMQUSDLEVMQNKNKUAUAAAOOMQDLUAAAOOUAB6MQUADLNKWNUSOOWNAAOOOOOOAAEVWNWNMQUSEVUSDLAAWNAAUAUSASEVDLMQWNDLAAWNB6DLAAUSOOOOUAUSAAAAOOAADLEVEVWNEVAAUAUADLAAOOOOWNWNAAWNOOWNUADLWNUAUAUAEVEVAAWNAAASEVMQWNOOEVWNEVEVWNUAWNAAEVDLOOWNUAUAEVWNOOF9F9UAWNAADLOOF9AAAAOOAAEVAAUSAAOOMQDLDLDLWNEVDLDLEVNKDLMQB6AAWNOOUAUSDLNKWNDLDLAAAAAADLWNWNOOUAAAUAWNDLUSDLUSWNEVNKOODLWNMQOOUAAAEVAAWNOOUSEVDLOOMQOODLASEVMQDLAAUSDLAAWNAAUADLF9WNOOAAWNWNF9OODLOOAAUAUSDLEVDLUADLDLMQUAEVWNAAMQWNUAUAEVMQMQOOEVOOEVEVMQEVUAWNDLUAUADLDLF9EVEVAAOOEVUAEVB6WNUADLDLWNWNAAUAWNUAOOAAWNAADLUAASEVEVUSWNWNAAOODLUADLWNVXEVWNVXUSOOWNOOWNWNDLWNF9MQEVDLUAAAEVEVWNDLUAAADLEVDLDLMQUSEVWNMQVXDLUAUSAAWNDLWNEVOOUAF9WNHAOOEVEVDLOODLDLDLWNDLUAOODLUADLAAUADLEVMQOOAAWNMQWNOOWNASDLAAAAWNUADLEVOOAAOOUSEVUAEVDLUAUADLUAVXMQOOUAWNWNAADLAADLWNDLDLDLOOWNOOAAEVAADLDLUSWNMQDLUADLAAUSWNUADLDLWNAAEVWNOODLWNEVUAWNUAUAUADLUSUADLUAMQUAUAWNOODLDLUAMQDLEVAAUSUSWNF9UADLAADLDLDLAAAAEVEVAADLDLUADLEVWNAAUSB6AAUSWNEVUSOOMQUAAAWNWNWNWNDLWNOODLWNMQWNAADLUAUAF9OOUAEVNKAAWNAAWNDLDLWNEVEVDLEVAAEVUAUSOOWNNKWNUSOOUAWNNKDLDLDLMQMQUAOOMQUAUADLUAWNDLDLNKNKEVOODLAANKOODLAAEVDLNKDLWNEVMQOOUAUAEVWNMQDLUAUADLWNAAOODLWNUAUSE

In [63]:
flights.sum() #컬럼별로 처리

MONTH                                                   363858
DAY                                                     918447
WEEKDAY                                                 229690
AIRLINE      WNUAMQAAWNUAAAF9AAUAMQEVOOEVUAAAOONKMQWNWNUAOO...
ORG_AIR      LAXDENDFWDFWLAXIAHDFWSFOORDIAHDFWORDORDORDIAHD...
DEST_AIR     SLCIADVPSDCAMCISANMSYPHXSTLSJCDROJANMSPCMHINDD...
SCHED_DEP                                             81186009
DEP_DELAY                                               629705
AIR_TIME                                           6.66288e+06
DIST                                                  51057671
SCHED_ARR                                             90627495
ARR_DELAY                                               334057
DIVERTED                                                   137
CANCELLED                                                  881
dtype: object

In [68]:
flights.select_dtypes(exclude='object').sum()

MONTH          363858.0
DAY            918447.0
WEEKDAY        229690.0
SCHED_DEP    81186009.0
DEP_DELAY      629705.0
AIR_TIME      6662879.0
DIST         51057671.0
SCHED_ARR    90627495.0
ARR_DELAY      334057.0
DIVERTED          137.0
CANCELLED         881.0
dtype: float64

In [65]:
flights.mean() #mean(), std(), var()은 숫자형 컬럼만 계산.

MONTH           6.220646
DAY            15.702096
WEEKDAY         3.926862
SCHED_DEP    1387.984836
DEP_DELAY      10.921192
AIR_TIME      115.928576
DIST          872.900072
SCHED_ARR    1549.399832
ARR_DELAY       5.812315
DIVERTED        0.002342
CANCELLED       0.015062
dtype: float64

In [70]:
flights.mean(skipna=False)

MONTH           6.220646
DAY            15.702096
WEEKDAY         3.926862
SCHED_DEP    1387.984836
DEP_DELAY            NaN
AIR_TIME             NaN
DIST          872.900072
SCHED_ARR    1549.399832
ARR_DELAY            NaN
DIVERTED        0.002342
CANCELLED       0.015062
dtype: float64

In [73]:
flights['DIST'].mean()

872.9000718046913

In [74]:
flights.describe()

,MONTH,DAY,WEEKDAY,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
count,58492.000000,58492.000000,58492.000000,58492.000000,57659.000000,57474.000000,58492.000000,58492.000000,57474.000000,58492.000000,58492.000000
mean,6.220646,15.702096,3.926862,1387.984836,10.921192,115.928576,872.900072,1549.399832,5.812315,0.002342,0.015062
std,3.358484,8.760846,1.995777,482.810792,36.146210,71.679591,624.996805,518.599952,38.411948,0.048340,0.121800
min,1.000000,1.000000,1.000000,5.000000,-24.000000,8.000000,67.000000,1.000000,-60.000000,0.000000,0.000000
25%,3.000000,8.000000,2.000000,1000.000000,-4.000000,61.000000,391.000000,1159.000000,-12.000000,0.000000,0.000000
50%,6.000000,16.000000,4.000000,1353.000000,-1.000000,97.000000,690.000000,1603.000000,-4.000000,0.000000,0.000000
75%,9.000000,23.000000,6.000000,1805.000000,10.000000,152.000000,1199.000000,1959.000000,9.000000,0.000000,0.000000
max,12.000000,31.000000,7.000000,2359.000000,1194.000000,577.000000,4502.000000,2359.000000,1185.000000,1.000000,1.000000

In [75]:
flights.describe(include='object')

       AIRLINE ORG_AIR DEST_AIR
count    58492   58492    58492
unique      14      10      271
top         DL     ATL      LAX
freq     10601   10413     1991

### aggregate(func, axis=0, \*args, \*\*kwargs) 또는 agg(func, axis=0, \*args, \*\*kwargs)
- 판다스가 제공하는 집계 함수들이나 사용자 정의 집계함수를 DataFrame의 열 별로 처리해주는 함수.
- **사용자 정의 집계함수를 사용하거나 열 별로 다른 집계를 할 때 사용한다.**
- 매개변수
    - func 
        - 집계 함수 지정
            - 문자열/문자열리스트 : 집계함수의 이름. 여러 개일 경우 리스트. 판다스 제공 집계함수는 문자열로 함수명만 제공가능
            - 딕셔너리 : {집계할컬럼 : 집계함수 }
            - 함수 객체 : 사용자 정의 함수의 경우 함수이름을 전달
    - axis
        - 0 또는 'index' (기본값): 컬럼 별 집계
        - 1 또는 'columns': 행 별 집계
    - \*args, \**kwargs 
        - 함수에 전달할 매개변수. 
        - 집계함수는 첫번째 매개변수로 Series를 받는다. 그 이외의 매개변수가 있는 경우.

In [85]:
# 평균
flights.aggregate('mean')

MONTH           6.220646
DAY            15.702096
WEEKDAY         3.926862
SCHED_DEP    1387.984836
DEP_DELAY      10.921192
AIR_TIME      115.928576
DIST          872.900072
SCHED_ARR    1549.399832
ARR_DELAY       5.812315
DIVERTED        0.002342
CANCELLED       0.015062
dtype: float64

In [81]:
# 평균, 합계
flights.aggregate(['mean', 'sum']).T

                mean                                                sum
MONTH        6.22065                                             363858
DAY          15.7021                                             918447
WEEKDAY      3.92686                                             229690
AIRLINE          NaN  WNUAMQAAWNUAAAF9AAUAMQEVOOEVUAAAOONKMQWNWNUAOO...
ORG_AIR          NaN  LAXDENDFWDFWLAXIAHDFWSFOORDIAHDFWORDORDORDIAHD...
DEST_AIR         NaN  SLCIADVPSDCAMCISANMSYPHXSTLSJCDROJANMSPCMHINDD...
SCHED_DEP    1387.98                                         8.1186e+07
DEP_DELAY    10.9212                                             629705
AIR_TIME     115.929                                        6.66288e+06
DIST           872.9                                        5.10577e+07
SCHED_ARR     1549.4                                        9.06275e+07
ARR_DELAY    5.81232                                             334057
DIVERTED   0.0023422                                                137
CANCELLED  0.0150619                                                881

In [87]:
flights['DIST'].agg(['sum','mean','count','median'])

sum       5.105767e+07
mean      8.729001e+02
count     5.849200e+04
median    6.900000e+02
Name: DIST, dtype: float64

In [91]:
flights.select_dtypes(exclude=['object']).agg(['sum','mean','count','median']).T

                  sum         mean    count  median
MONTH        363858.0     6.220646  58492.0     6.0
DAY          918447.0    15.702096  58492.0    16.0
WEEKDAY      229690.0     3.926862  58492.0     4.0
SCHED_DEP  81186009.0  1387.984836  58492.0  1353.0
DEP_DELAY    629705.0    10.921192  57659.0    -1.0
AIR_TIME    6662879.0   115.928576  57474.0    97.0
DIST       51057671.0   872.900072  58492.0   690.0
SCHED_ARR  90627495.0  1549.399832  58492.0  1603.0
ARR_DELAY    334057.0     5.812315  57474.0    -4.0
DIVERTED        137.0     0.002342  58492.0     0.0
CANCELLED       881.0     0.015062  58492.0     0.0

In [93]:
#AIRLINE : 최빈값-mode, DEP_DELAY: 평균-mean
flights.agg({'AIRLINE':'mode', 'DEP_DELAY':'mean'})

  AIRLINE  DEP_DELAY
0      DL  10.921192

In [94]:
#AIRLINE : 최빈값-mode, DEP_DELAY: 평균-mean, 표준편차-std
flights.agg({'AIRLINE':'mode', 'DEP_DELAY':['mean', 'std']})

     AIRLINE  DEP_DELAY
        mode  DEP_DELAY
0         DL        NaN
mean     NaN  10.921192
std      NaN  36.146210

In [97]:
# ARR_DELAY, DEP_DELAY의 min, max
flights[['ARR_DELAY', 'DEP_DELAY']].agg(['min', 'max'])

     ARR_DELAY  DEP_DELAY
min      -60.0      -24.0
max     1185.0     1194.0

In [104]:
flights['ARR_DELAY'].quantile(q=[0.25,0.75]) #분위수 - 기본: 중앙값

-4.0

In [105]:
flights['ARR_DELAY'].agg('quantile', q=[0.25, 0.75])

0.25   -12.0
0.75     9.0
Name: ARR_DELAY, dtype: float64

In [ ]:
select mean(ARR_DELAY)
from   flights
group by AIRLINE

# Groupby
- 특정 열을 기준으로 데이터셋을 묶는다.
- ~~ 별 집계를 할 때 사용한다.
- 구문
    - DF.groupby('그룹으로묶을기준컬럼')['집계할 컬럼'].집계함수()
        - 집계할 컬럼은 Fancy Indexing 으로 지정(리스트, 튜플로 전달)
    - 집계함수
        - 기술통계 함수들
        - agg()/aggregate()
            - 여러 다른 집계함수 호출시(여러 집계를 같이 볼경우)
            - 사용자정의 집계함수 호출시
            - 컬럼별로 다른 집계함수들을 호출할 경우


- ### 가장 많이 쓰이는 것은 마지막 집계함수를 직접 호출 하는 것
- ### 한번에 여러개의 집계함수를 호출 할 경우는 agg([리스트]) 를 사용한다.
- ### 열별로 다른 집계를 하는 경우 dict를 사용한다.

In [107]:
np.sort(flights['AIRLINE'].unique())

array(['AA', 'AS', 'B6', 'DL', 'EV', 'F9', 'HA', 'MQ', 'NK', 'OO', 'UA',
       'US', 'VX', 'WN'], dtype=object)

In [109]:
gb = flights.groupby('AIRLINE')
type(gb)

pandas.core.groupby.generic.DataFrameGroupBy

In [111]:
from pprint import pprint
pprint(gb.groups)

{'AA': Int64Index([    3,     6,     8,    15,    26,    32,    33,    36,    37,
               41,
            ...
            58454, 58456, 58462, 58465, 58466, 58470, 58475, 58476, 58479,
            58487],
           dtype='int64', length=8900),
 'AS': Int64Index([   38,   198,   241,   277,   397,   450,   453,   500,   518,
              591,
            ...
            58202, 58207, 58224, 58238, 58253, 58305, 58355, 58404, 58407,
            58428],
           dtype='int64', length=768),
 'B6': Int64Index([  123,   127,   239,   333,   548,   549,   696,   757,   945,
             1175,
            ...
            57948, 57968, 58059, 58076, 58228, 58262, 58301, 58425, 58477,
            58483],
           dtype='int64', length=543),
 'DL': Int64Index([   53,    57,    77,    79,    85,    90,    91,   101,   116,
              117,
            ...
            58390, 58411, 58413, 58421, 58429, 58440, 58448, 58464, 58467,
            58485],
           dtype='int64', length=10601),
 'EV': Int64Index([   11,    13,    29,    40,    69,   100,   106,   118,   136,
              143,
            ...
            58370, 58397, 58412, 58423, 58438, 58445, 58452, 58459, 58463,
            58486],
           dtype='int64', length=5858),
 'F9': Int64Index([    7,    93,   209,   232,   247,   290,   301,   386,   444,
              483,
            ...
            58151, 58169, 58194, 58201, 58219, 58288, 58331, 58447, 58449,
            58488],
           dtype='int64', length=1317),
 'HA': Int64Index([  582,   712,   878,  1053,  1269,  1345,  1544,  1864,  2316,
             2644,
            ...
            53204, 53338, 54457, 55215, 55679, 55883, 56174, 56350, 56816,
            58391],
           dtype='int64', length=112),
 'MQ': Int64Index([    2,    10,    18,    24,    50,    60,    71,    78,    81,
              103,
            ...
            58369, 58393, 58394, 58406, 58410, 58415, 58426, 58468, 58474,
            58484],
           dtype='int64', length=3471),
 'NK': Int64Index([   17,    74,    95,   109,   166,   345,   358,   401,   434,
              436,
            ...
            58006, 58022, 58113, 58129, 58152, 58160, 58197, 58437, 58461,
            58469],
           dtype='int64', length=1516),
 'OO': Int64Index([   12,    16,    22,    25,    27,    34,    39,    42,    51,
               52,
            ...
            58433, 58434, 58435, 58439, 58446, 58451, 58480, 58482, 58489,
            58491],
           dtype='int64', length=6588),
 'UA': Int64Index([    1,     5,     9,    14,    21,    44,    45,    67,    70,
               72,
            ...
            58365, 58389, 58396, 58401, 58419, 58422, 58432, 58457, 58460,
            58481],
           dtype='int64', length=7792),
 'US': Int64Index([   31,    35,    49,    96,   104,   111,   112,   119,   148,
              150,
            ...
            31433, 31445, 31462, 31481, 31497, 31514, 31523, 31535, 31561,
            31582],
           dtype='int64', length=1615),
 'VX': Int64Index([   56,   227,   243,   417,   432,   464,   614,   641,   703,
              759,
            ...
            57971, 58068, 58112, 58298, 58313, 58332, 58383, 58400, 58471,
            58478],
           dtype='int64', length=993),
 'WN': Int64Index([    0,     4,    19,    20,    23,    28,    30,    43,    59,
               64,
            ...
            58408, 58409, 58430, 58436, 58444, 58455, 58458, 58472, 58473,
            58490],
           dtype='int64', length=8418)}

In [113]:
flights.iloc[[3,     6,     8,    15,    26,    32,    33,    36,    37,41]]

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
3,1,1,4,AA,DFW,DCA,1555,7.0,126.0,1192,1935,-7.0,0,0
6,1,1,4,AA,DFW,MSY,1250,84.0,64.0,447,1410,83.0,0,0
8,1,1,4,AA,ORD,STL,1845,-5.0,44.0,258,1950,-5.0,0,0
15,1,1,4,AA,DEN,DFW,1445,-6.0,93.0,641,1745,4.0,0,0
26,1,1,4,AA,LAX,AUS,1430,33.0,157.0,1242,1925,41.0,0,0
32,1,1,4,AA,PHX,MIA,1559,115.0,230.0,1972,2203,117.0,0,0
33,1,1,4,AA,IAH,MIA,1935,26.0,115.0,964,2256,21.0,0,0
36,1,1,4,AA,DFW,OKC,1345,5.0,35.0,175,1440,6.0,0,0
37,1,1,4,AA,LAS,DFW,1210,12.0,132.0,1055,1650,17.0,0,0
41,1,1,4,AA,DFW,DCA,2010,19.0,126.0,1192,2350,4.0,0,0

In [115]:
# flights[flights['AIRLINE']=='AA']

In [119]:
# AIRLINE 별 각 컬럼의 평균
flights.groupby('AIRLINE').mean()

,MONTH,DAY,WEEKDAY,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
AIRLINE,,,,,,,,,,,
AA,6.661461,15.570562,3.986966,1340.140449,11.274057,144.259404,1114.347865,1546.960899,5.542661,0.002921,0.017303
AS,6.197917,15.247396,3.941406,1418.269531,1.808594,147.845052,1065.884115,1548.292969,-0.833333,0.000000,0.000000
B6,6.368324,15.788214,4.040516,1512.924494,14.287823,209.412963,1771.882136,1432.889503,8.692593,0.003683,0.001842
DL,6.277332,15.721158,3.913310,1426.563154,7.242450,115.334187,866.448448,1578.735402,0.339691,0.002264,0.003585
EV,6.003926,15.866166,3.927450,1415.510413,9.092625,68.964016,460.237453,1571.798054,7.034580,0.002561,0.024923
F9,6.401670,15.914958,4.007593,1407.121488,14.310398,127.592337,969.593014,1510.177677,13.630651,0.001519,0.007593
HA,5.508929,15.526786,3.750000,959.419643,2.571429,338.288288,2615.178571,1280.714286,4.972973,0.008929,0.000000
MQ,5.970614,15.598963,3.902622,1432.251801,11.094323,61.318346,404.229041,1587.835494,6.860591,0.001441,0.043791
NK,6.602243,15.680739,4.006596,1336.634565,19.514401,135.736878,1047.428100,1398.226913,18.436070,0.003298,0.016491
OO,6.134791,15.651943,3.923345,1426.486794,9.662279,76.010272,511.239375,1573.730267,7.593463,0.003188,0.021554
UA,6.322510,15.697510,3.871535,1357.970739,16.210485,155.650521,1230.918891,1532.871150,7.765755,0.002438,0.011935
US,3.628483,16.079876,4.063777,1289.552941,4.361355,147.686755,1181.226625,1489.131269,1.681105,0.000619,0.013003
VX,6.336354,15.518630,3.924471,1385.110775,8.918946,154.864097,1240.296073,1581.023162,5.348884,0.001007,0.006042
WN,6.298646,15.746971,3.884652,1370.585650,12.639366,107.005897,809.985626,1532.243407,6.397353,0.001782,0.011048

In [121]:
# AIRLINE 별 AIR_TIME의 평균
np.round(flights.groupby('AIRLINE')['AIR_TIME'].mean(),2)

AIRLINE
AA    144.26
AS    147.85
B6    209.41
DL    115.33
EV     68.96
F9    127.59
HA    338.29
MQ     61.32
NK    135.74
OO     76.01
UA    155.65
US    147.69
VX    154.86
WN    107.01
Name: AIR_TIME, dtype: float64

In [ ]:
SELECT avg(AIR_TIME)
FROM   flights
GROUP BY AIRLINE

In [122]:
flights.groupby('AIRLINE')[['ARR_DELAY', 'DEP_DELAY']].mean()

         ARR_DELAY  DEP_DELAY
AIRLINE
AA        5.542661  11.274057
AS       -0.833333   1.808594
B6        8.692593  14.287823
DL        0.339691   7.242450
EV        7.034580   9.092625
F9       13.630651  14.310398
HA        4.972973   2.571429
MQ        6.860591  11.094323
NK       18.436070  19.514401
OO        7.593463   9.662279
UA        7.765755  16.210485
US        1.681105   4.361355
VX        5.348884   8.918946
WN        6.397353  12.639366

In [124]:
# flights.groupby('AIRLINE')['ARR_DELAY', 'DEP_DELAY'].mean()

In [126]:
flights.groupby('AIRLINE')['ARR_DELAY'].agg(['mean', 'std'])

              mean        std
AIRLINE
AA        5.542661  43.323160
AS       -0.833333  31.168354
B6        8.692593  40.221718
DL        0.339691  32.299471
EV        7.034580  36.682336
F9       13.630651  53.030912
HA        4.972973  37.528283
MQ        6.860591  36.324657
NK       18.436070  48.727259
OO        7.593463  35.331344
UA        7.765755  46.405935
US        1.681105  27.030227
VX        5.348884  33.747675
WN        6.397353  32.610666

In [128]:
result = flights.groupby('AIRLINE')[['ARR_DELAY','DEP_DELAY', 'AIR_TIME']].agg(['mean', 'std'])
result

         ARR_DELAY             DEP_DELAY               AIR_TIME
              mean        std       mean        std        mean         std
AIRLINE
AA        5.542661  43.323160  11.274057  40.787806  144.259404   72.871103
AS       -0.833333  31.168354   1.808594  29.543702  147.845052   59.821928
B6        8.692593  40.221718  14.287823  36.863416  209.412963   97.466125
DL        0.339691  32.299471   7.242450  29.759377  115.334187   71.027396
EV        7.034580  36.682336   9.092625  34.582917   68.964016   31.735348
F9       13.630651  53.030912  14.310398  51.773844  127.592337   46.832304
HA        4.972973  37.528283   2.571429  33.880743  338.288288   29.329906
MQ        6.860591  36.324657  11.094323  31.159293   61.318346   29.409990
NK       18.436070  48.727259  19.514401  46.484632  135.736878   57.031164
OO        7.593463  35.331344   9.662279  33.413767   76.010272   42.394403
UA        7.765755  46.405935  16.210485  44.834336  155.650521   78.933987
US        1.681105  27.030227   4.361355  24.550930  147.686755   75.083131
VX        5.348884  33.747675   8.918946  31.782085  154.864097  100.970317
WN        6.397353  32.610666  12.639366  30.506549  107.005897   55.778468

In [129]:
result['ARR_DELAY']

              mean        std
AIRLINE
AA        5.542661  43.323160
AS       -0.833333  31.168354
B6        8.692593  40.221718
DL        0.339691  32.299471
EV        7.034580  36.682336
F9       13.630651  53.030912
HA        4.972973  37.528283
MQ        6.860591  36.324657
NK       18.436070  48.727259
OO        7.593463  35.331344
UA        7.765755  46.405935
US        1.681105  27.030227
VX        5.348884  33.747675
WN        6.397353  32.610666

In [131]:
result['ARR_DELAY', 'mean']

AIRLINE
AA     5.542661
AS    -0.833333
B6     8.692593
DL     0.339691
EV     7.034580
F9    13.630651
HA     4.972973
MQ     6.860591
NK    18.436070
OO     7.593463
UA     7.765755
US     1.681105
VX     5.348884
WN     6.397353
Name: (ARR_DELAY, mean), dtype: float64

In [148]:
# 컬럼별로 다른 통계량을 조회
flights.groupby('AIRLINE').agg({"DEP_DELAY":['mean', 'std'], 
                                'ARR_DELAY':['min', 'max'], 
                                'AIR_TIME':'count'})

         DEP_DELAY            ARR_DELAY         AIR_TIME
              mean        std       min     max    count
AIRLINE
AA       11.274057  40.787806     -60.0   858.0     8720
AS        1.808594  29.543702     -57.0   344.0      768
B6       14.287823  36.863416     -51.0   331.0      540
DL        7.242450  29.759377     -57.0   741.0    10539
EV        9.092625  34.582917     -39.0   669.0     5697
F9       14.310398  51.773844     -43.0   839.0     1305
HA        2.571429  33.880743     -44.0   298.0      111
MQ       11.094323  31.159293     -37.0   357.0     3314
NK       19.514401  46.484632     -39.0   474.0     1486
OO        9.662279  33.413767     -44.0   724.0     6425
UA       16.210485  44.834336     -58.0  1185.0     7680
US        4.361355  24.550930     -51.0   431.0     1593
VX        8.918946  31.782085     -51.0   236.0      986
WN       12.639366  30.506549     -52.0   493.0     8310

In [136]:
#취소여부(CANCELLED): 0-False(취소안됨), 1-True(취소)
flights['CANCELLED'].value_counts()

0    57611
1      881
Name: CANCELLED, dtype: int64

In [140]:
# 항공사별 취소 건수
flights.groupby('AIRLINE')['CANCELLED'].sum()

AIRLINE
AA    154
AS      0
B6      1
DL     38
EV    146
F9     10
HA      0
MQ    152
NK     25
OO    142
UA     93
US     21
VX      6
WN     93
Name: CANCELLED, dtype: int64

In [143]:
# index기준으로 groupby
# df.groupby(df.index)
df = pd.DataFrame(np.arange(15).reshape(5,3), index=['A','A','A','B','B'], columns=['가','나','다'])
df

    가   나   다
A   0   1   2
A   3   4   5
A   6   7   8
B   9  10  11
B  12  13  14

In [144]:
df.index

Index(['A', 'A', 'A', 'B', 'B'], dtype='object')

In [145]:
df.groupby(df.index).mean()

      가     나     다
A   3.0   4.0   5.0
B  10.5  11.5  12.5

###  복수열 기준 그룹핑
- 두개 이상의 열을 그룹으로 묶을 수 있다. 
- groupby의 매개변수에 그룹으로 묶을 컬럼들의 이름을 리스트로 전달한다.

In [147]:
#AIRLINE, MONTH기준
flights.groupby(['AIRLINE', 'MONTH'])['DEP_DELAY'].mean()

AIRLINE  MONTH
AA       1        12.645740
         2         8.485816
         3        13.536337
         4         9.127352
         5        12.552995
                    ...
WN       7        18.904110
         8        12.123253
         9         6.240152
         11        8.548344
         12       14.622222
Name: DEP_DELAY, Length: 149, dtype: float64

In [150]:
flights.groupby(['AIRLINE', 'MONTH'])[['DEP_DELAY', 'ARR_DELAY']].mean()

               DEP_DELAY  ARR_DELAY
AIRLINE MONTH
AA      1      12.645740   9.436282
        2       8.485816   6.262032
        3      13.536337  10.639535
        4       9.127352   1.503628
        5      12.552995   7.549231
...                  ...        ...
WN      7      18.904110  13.458750
        8      12.123253   6.542675
        9       6.240152  -1.232824
        11      8.548344   1.846154
        12     14.622222   8.947575

[149 rows x 2 columns]

In [152]:
result = flights.groupby(['AIRLINE', 'MONTH'])[['DEP_DELAY', 'ARR_DELAY']].agg(['mean','sum'])
result

               DEP_DELAY           ARR_DELAY
                    mean      sum       mean      sum
AIRLINE MONTH
AA      1      12.645740   8460.0   9.436282   6294.0
        2       8.485816   4786.0   6.262032   3513.0
        3      13.536337   9313.0  10.639535   7320.0
        4       9.127352   6307.0   1.503628   1036.0
        5      12.552995   8172.0   7.549231   4907.0
...                  ...      ...        ...      ...
WN      7      18.904110  15180.0  13.458750  10767.0
        8      12.123253   9541.0   6.542675   5136.0
        9       6.240152   4911.0  -1.232824   -969.0
        11      8.548344   6454.0   1.846154   1392.0
        12     14.622222  11186.0   8.947575   6827.0

[149 rows x 4 columns]

In [153]:
result.loc['AA']

       DEP_DELAY           ARR_DELAY
            mean      sum       mean     sum
MONTH
1      12.645740   8460.0   9.436282  6294.0
2       8.485816   4786.0   6.262032  3513.0
3      13.536337   9313.0  10.639535  7320.0
4       9.127352   6307.0   1.503628  1036.0
5      12.552995   8172.0   7.549231  4907.0
6      17.547684  12880.0   9.968493  7277.0
7      13.305985  13785.0   6.959302  7182.0
8      11.137295  10870.0   3.289990  3188.0
9       6.205819   5759.0  -0.544276  -504.0
11     10.916575   9945.0   4.450441  4041.0
12      9.280488   8371.0   4.531111  4078.0

In [155]:
result.loc['AA', 12]

DEP_DELAY  mean       9.280488
           sum     8371.000000
ARR_DELAY  mean       4.531111
           sum     4078.000000
Name: (AA, 12), dtype: float64

In [ ]:
SELECT
FROM   EMP
GROUP BY DEPT
HAVING avg(salary) > 10000

## Goupby 집계후 집계한 것 중 특정 조건의 항목만 보기
- SQL having 절
- 집계 후 boolean indexing으로 having절 처리

In [162]:
# 항공사별로 취소한 횟수가 50건 이상인 것만 조회
result = flights.groupby('AIRLINE')['CANCELLED'].sum() 
result[result>=50]

AIRLINE
AA    154
EV    146
MQ    152
OO    142
UA     93
WN     93
Name: CANCELLED, dtype: int64

## 사용자 정의 집계함수를 만들어 적용

### 사용자 정의 집계 함수 정의
- 매개변수
    1. Series 또는 DataFrame을 받을 매개변수(필수)
    2. 필요한 값을 받을 매개변수를 선언한다. (선택)

### agg() 를 사용해 사용자 정의 집계 함수 호출
- DataFrame.agg(func=None, axis=0, \*args, \*\*kwargs)
    - axis : 사용자 정의 함수에 전달할 값들(Series)의 축 지정
- Series.agg(func=None, axis=0, \*args, \*\*kwargs)
    - DataFrame의 agg와 매개변수 구조를 맞추기 위해 axis 지정한다. 
- SeriesGroupBy.agg(func=None,  \*args, \*\*kwargs)  
    - axis 지정안함
    - 사용자 함수에 Series를 group 별로 전달한다.
- DataFrameGroupBy.agg(func, \*args, \*\*kwargs)  
    - axis 지정안함.
    - 사용자 함수에 Series를 group 별로 전달한다. 
- \*args, \*\*kwargs는 사용자 정의 함수에 선언한 매개변수가 있을 경우 전달할 값을 전달한다.

In [172]:
# max와 min값의 차이를 반환하는 사용자정의 집계함수
def max_min_diff(x):
    """
    max와 min값의 차이를 반환하는 사용자정의 집계함수
    [매개변수]
        x: 통계량을 구할 Series
    [반환값]
        max()-min()
        Series x의 타입이 object(문자열)이면 None을 반환
    """
    if x.dtype == 'object':
        return None
    return x.max() - x.min()

In [174]:
max_min_diff(flights['ARR_DELAY'])

1245.0

In [176]:
flights['ARR_DELAY'].agg(max_min_diff) #사용자정의 집계함수 객체를 매개변수로 전달.

1245.0

In [177]:
flights['ARR_DELAY'].agg(['max','min', max_min_diff])

max             1185.0
min              -60.0
max_min_diff    1245.0
Name: ARR_DELAY, dtype: float64

In [180]:
flights.agg(['max', 'min', max_min_diff])

,MONTH,DAY,WEEKDAY,AIRLINE,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
max,12,31,7,WN,SFO,YUM,2359,1194.0,577.0,4502,2359,1185.0,1,1
min,1,1,1,AA,ATL,ABE,5,-24.0,8.0,67,1,-60.0,0,0
max_min_diff,11,30,6,None,None,None,2354,1218.0,569.0,4435,2358,1245.0,1,1

In [181]:
flights.groupby('AIRLINE').agg(max_min_diff)

,MONTH,DAY,WEEKDAY,ORG_AIR,DEST_AIR,SCHED_DEP,DEP_DELAY,AIR_TIME,DIST,SCHED_ARR,ARR_DELAY,DIVERTED,CANCELLED
AIRLINE,,,,,,,,,,,,,
AA,11,30,6,None,None,2354,850.0,484.0,3609,2358,918.0,1,1
AS,11,30,6,None,None,1755,360.0,344.0,2425,2358,401.0,0,0
B6,11,30,6,None,None,1819,367.0,304.0,2473,2352,382.0,1,1
DL,11,30,6,None,None,2354,772.0,555.0,4396,2358,798.0,1,1
EV,11,30,6,None,None,1712,689.0,198.0,1256,2357,708.0,1,1
F9,11,30,6,None,None,2354,871.0,241.0,1845,2354,882.0,1,1
HA,11,30,6,None,None,1680,322.0,130.0,579,1635,342.0,1,0
MQ,11,30,6,None,None,1845,354.0,183.0,1161,2356,394.0,1,1
NK,11,30,6,None,None,2345,477.0,256.0,2145,2354,513.0,1,1
OO,11,30,6,None,None,2352,755.0,250.0,1668,2358,768.0,1,1
UA,11,30,6,None,None,2352,1212.0,519.0,4135,2358,1243.0,1,1
US,5,30,6,None,None,2348,454.0,377.0,2753,2355,482.0,1,1
VX,11,30,6,None,None,2345,266.0,308.0,2468,2234,287.0,1,1
WN,11,30,6,None,None,1795,490.0,291.0,2132,2350,545.0,1,1

In [182]:
# 매개변수가 있는 사용자 정의 집계 함수.
# max가 100이상인지 여부
def check_max(series, n=100):
    if series.dtype != 'object':
        return series.max() >= n

In [187]:
check_max(flights['ARR_DELAY'], n=2000)

True

In [188]:
flights['ARR_DELAY'].agg(check_max, n=2000)

False

In [194]:
flights.groupby('AIRLINE')['ARR_DELAY'].agg(check_max, n=1000)

AIRLINE
AA    False
AS    False
B6    False
DL    False
EV    False
F9    False
HA    False
MQ    False
NK    False
OO    False
UA     True
US    False
VX    False
WN    False
Name: ARR_DELAY, dtype: bool

In [191]:
flights.groupby('AIRLINE')['ARR_DELAY'].max()

AIRLINE
AA     858.0
AS     344.0
B6     331.0
DL     741.0
EV     669.0
F9     839.0
HA     298.0
MQ     357.0
NK     474.0
OO     724.0
UA    1185.0
US     431.0
VX     236.0
WN     493.0
Name: ARR_DELAY, dtype: float64

# TODO
1. data/diamonds.csv 를 읽어 DataFrame 생성
2. 1에서 생성한 DataFrame의 정보 조회
    - 배열의 shape조회
    - 컬럼들의 정보조회
    - 상/하위 5개 행 조회
3. cut별 가격 평균 조회
4. clarity별 carat 평균과 표준편차 조회
5. cut과 color 별로 가격은 평균을 carat은 최대값을 조회

In [1]:
# data/diamonds.csv 를 읽어 DataFrame 생성
import pandas as pd
import numpy as np

dia_df = pd.read_csv('data/diamonds.csv')

In [2]:
# 1에서 생성한 DataFrame의 정보 조회
dia_df.shape

(53940, 10)

In [3]:
dia_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  object
 2   color    53940 non-null  object
 3   clarity  53940 non-null  object
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [4]:
dia_df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [5]:
dia_df['cut'].value_counts()

Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: cut, dtype: int64

In [7]:
dia_df['color'].value_counts()

G    11292
E     9797
F     9542
H     8304
D     6775
I     5422
J     2808
Name: color, dtype: int64

In [8]:
dia_df['clarity'].value_counts()

SI1     13065
VS2     12258
SI2      9194
VS1      8171
VVS2     5066
VVS1     3655
IF       1790
I1        741
Name: clarity, dtype: int64

In [9]:
dia_df.describe()

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [11]:
# cut별 가격 평균 조회
dia_df.groupby('cut')['price'].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [13]:
# clarity별 carat 평균과 표준편차 조회
dia_df.groupby('clarity')['carat'].agg(['mean', 'std', 'median'])

             mean       std  median
clarity
I1       1.283846  0.632436    1.12
IF       0.505123  0.313433    0.35
SI1      0.850482  0.449652    0.76
SI2      1.077648  0.516653    1.01
VS1      0.727158  0.423529    0.57
VS2      0.763935  0.446292    0.63
VVS1     0.503321  0.299557    0.39
VVS2     0.596202  0.359697    0.44

In [14]:
# cut과 color 별로 가격은 평균을 carat은 최대값을 조회
dia_df.groupby(['cut', 'color']).agg({'price':'mean', 'carat':'max'})

                       price  carat
cut       color
Fair      D      4291.061350   3.40
          E      3682.312500   2.04
          F      3827.003205   2.58
          G      4239.254777   2.60
          H      5135.683168   4.13
          I      4685.445714   3.02
          J      4975.655462   5.01
Good      D      3405.382175   2.04
          E      3423.644159   3.00
          F      3495.750275   2.67
          G      4123.482204   2.80
          H      4276.254986   3.01
          I      5078.532567   3.01
          J      4574.172638   3.00
Ideal     D      2629.094566   2.75
          E      2597.550090   2.28
          F      3374.939362   2.45
          G      3720.706388   2.54
          H      3889.334831   3.50
          I      4451.970377   3.22
          J      4918.186384   3.01
Premium   D      3631.292576   2.57
          E      3538.914420   3.05
          F      4324.890176   3.01
          G      4500.742134   3.01
          H      5216.706780   3.24
          I      5946.180672   4.01
          J      6294.591584   4.01
Very Good D      3470.467284   2.58
          E      3214.652083   2.51
          F      3778.820240   2.48
          G      3872.753806   2.52
          H      4535.390351   3.00
          I      5255.879568   4.00
          J      5103.513274   2.74